<a href="https://colab.research.google.com/github/andre2564/SistemaPredictivoAtaquesCardiacos/blob/main/Parcial_2_Preparacion_de_los_datos_Resuelto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Parcial 2 - Preparación de los datos**

En este trabajo se busca preparar los datos de un dataset para un proyecto de analítica de datos.


**Consideraciones**

* Lea estas consideraciones!!!
* Solo modifique las celdas que le son indicadas.
* Asegurese de incluir la documentación (**Con ortografía**, si no quieren perder puntos) para cada una de las fucniones construídas.

# Sistemas de prediccion de Ataques Cardiacos

**Datos de la presentación**


* **Curso**: 901T

* **Autores**:

1. Andrea Roa Perez

# Fase 1: Preparación de los datos

##Importacion de librerias

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Librerias a utilizar
import numpy                as np
import pandas               as pd
import matplotlib.pyplot    as plt
import seaborn              as sns

import folium               #needed for interactive map
from folium.plugins import HeatMap

#limites columnas
pd.options.display.max_columns = None

#limites filas
#pd.options.display.max_rows = None

##Importacion Dataset

In [ ]:
#importacion dataframe

#df=pd.read_csv("/content/drive/MyDrive/Electiva Profesional DATOS III/viables/2015.csv/2015.csv") 
df=pd.read_csv("/content/drive/MyDrive/data/muestra.csv") 
df

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENUM,PVTRESD1,COLGHOUS,STATERES,CELLFON3,LADULT,NUMADULT,NUMMEN,NUMWOMEN,CTELNUM1,CELLFON2,CADULT,PVTRESD2,CCLGHOUS,CSTATE,LANDLINE,HHADULT,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,HLTHPLN1,PERSDOC2,MEDCOST,CHECKUP1,BPHIGH4,BPMEDS,BLOODCHO,CHOLCHK,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,ASTHNOW,CHCSCNCR,CHCOCNCR,CHCCOPD1,HAVARTH3,ADDEPEV2,CHCKIDNY,DIABETE3,DIABAGE2,SEX,MARITAL,EDUCA,RENTHOM1,NUMHHOL2,NUMPHON2,CPDEMO1,VETERAN3,EMPLOY1,CHILDREN,INCOME2,INTERNET,WEIGHT2,HEIGHT3,PREGNANT,QLACTLM2,USEEQUIP,BLIND,DECIDE,DIFFWALK,DIFFDRES,DIFFALON,SMOKE100,SMOKDAY2,STOPSMK2,LASTSMK2,USENOW3,ALCDAY5,AVEDRNK2,DRNK3GE5,MAXDRNKS,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,EXRACT11,EXEROFT1,EXERHMM1,EXRACT21,EXEROFT2,EXERHMM2,STRENGTH,LMTJOIN3,ARTHDIS2,ARTHSOCL,JOINPAIN,SEATBELT,FLUSHOT6,FLSHTMY2,IMFVPLAC,PNEUVAC3,HIVTST6,HIVTSTD3,WHRTST10,PDIABTST,PREDIAB1,INSULIN,BLDSUGAR,FEETCHK2,DOCTDIAB,CHKHEMO3,FEETCHK,EYEEXAM,DIABEYE,DIABEDU,PAINACT2,QLMENTL2,QLSTRES2,QLHLTH2,CAREGIV1,CRGVREL1,CRGVLNG1,CRGVHRS1,CRGVPRB1,CRGVPERS,CRGVHOUS,CRGVMST2,CRGVEXPT,VIDFCLT2,VIREDIF3,VIPRFVS2,VINOCRE2,VIEYEXM2,VIINSUR2,VICTRCT4,VIGLUMA2,VIMACDG2,CIMEMLOS,CDHOUSE,CDASSIST,CDHELP,CDSOCIAL,CDDISCUS,WTCHSALT,LONGWTCH,DRADVISE,ASTHMAGE,ASATTACK,ASERVIST,ASDRVIST,ASRCHKUP,ASACTLIM,ASYMPTOM,ASNOSLEP,ASTHMED3,ASINHALR,HAREHAB1,STREHAB1,CVDASPRN,ASPUNSAF,RLIVPAIN,RDUCHART,RDUCSTRK,ARTTODAY,ARTHWGT,ARTHEXER,ARTHEDU,TETANUS,HPVADVC2,HPVADSHT,SHINGLE2,HADMAM,HOWLONG,HADPAP2,LASTPAP2,HPVTEST,HPLSTTST,HADHYST2,PROFEXAM,LENGEXAM,BLDSTOOL,LSTBLDS3,HADSIGM3,HADSGCO1,LASTSIG3,PCPSAAD2,PCPSADI1,PCPSARE1,PSATEST1,PSATIME,PCPSARS1,PCPSADE1,PCDMDECN,SCNTMNY1,SCNTMEL1,SCNTPAID,SCNTWRK1,SCNTLPAD,SCNTLWK1,SXORIENT,TRNSGNDR,RCSGENDR,RCSRLTN2,CASTHDX2,CASTHNO2,EMTSUPRT,LSATISFY,ADPLEASR,ADDOWN,ADSLEEP,ADENERGY,ADEAT1,ADFAIL,ADTHINK,ADMOVE,MISTMNT,ADANXEV,QSTVER,QSTLANG,EXACTOT1,EXACTOT2,MSCODE,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_CHISPNC,_CRACE1,_CPRACE,_CLLCPWT,_DUALUSE,_DUALCOR,_LLCPWT,_RFHLTH,_HCVU651,_RFHYPE5,_CHOLCHK,_RFCHOL,_MICHD,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR1,_PRACE1,_MRACE1,_HISPANC,_RACE,_RACEG21,_RACEGR3,_RACE_G1,_AGEG5YR,_AGE65YR,_AGE80,_AGE_G,HTIN4,HTM4,WTKG3,_BMI5,_BMI5CAT,_RFBMI5,_CHLDCNT,_EDUCAG,_INCOMG,_SMOKER3,_RFSMOK3,DRNKANY5,DROCDY3_,_RFBING5,_DRNKWEK,_RFDRHV5,FTJUDA1_,FRUTDA1_,BEANDAY_,GRENDAY_,ORNGDAY_,VEGEDA1_,_MISFRTN,_MISVEGN,_FRTRESP,_VEGRESP,_FRUTSUM,_VEGESUM,_FRTLT1,_VEGLT1,_FRT16,_VEG23,_FRUITEX,_VEGETEX,_TOTINDA,METVL11_,METVL21_,MAXVO2_,FC60_,ACTIN11_,ACTIN21_,PADUR1_,PADUR2_,PAFREQ1_,PAFREQ2_,_MINAC11,_MINAC21,STRFREQ_,PAMISS1_,PAMIN11_,PAMIN21_,PA1MIN_,PAVIG11_,PAVIG21_,PA1VIGM_,_PACAT1,_PAINDX1,_PA150R2,_PA300R2,_PA30021,_PASTRNG,_PAREC1,_PASTAE1,_LMTACT1,_LMTWRK1,_LMTSCL1,_RFSEAT2,_RFSEAT3,_FLSHOT6,_PNEUMO2,_AIDTST3
0,1.0,1.0,b'01292015',b'01',b'29',b'2015',1200.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,3.0,1.000000e+00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,15.0,18.0,10.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,3.0,NaN,2.0,1.0,4.0,1.0,2.0,NaN,1.0,2.0,8.0,88.0,3.0,2.0,280.0,510.0,NaN,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,3.0,NaN,2.0,3.0,888.0,NaN,NaN,NaN,305.0,310.0,320.0,310.0,305.0,101.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,1.0,1.0,1.0,6.0,1.0,1.0,112014.0,1.0,1.0,1.0,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',3.0,11011.0,28.781560,3.0,86.344681,NaN,NaN,NaN,NaN,1.0,0.614125,341.384853,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,9.0,1.0,63.0,5.0,70.0,178.0,12701.0,4018.0,4.0,2.0,1.0,2.0,2.0,3.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.700000e+01,33.0,6.700000e+01,33.0,17.0,100.0,5.397605e-79,5.397605e-79,1.000000e+00,1.000000e+00,50.0,217.0,2.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,2.0,NaN,NaN,2469.0,423.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.397605e-79,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,3.0,3.0,2.0,2.0,4.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,1.0
1,1.0,1.0,b'01202015',b'01',b'20',b'2015',1100.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,1.0,5.397605e-79,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,88.0,88.0,NaN,2.0,1.0,1.0,4.0,3.0,NaN,1.0,4.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,2.0,2.0,6.0,1.0,2.0,NaN,2.0,2.0,3.0,88.0,1.0,1.0,165.0,508.0,NaN,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,NaN,3.0,888.0,NaN,NaN,NaN,302.0,305.0,302.0,202.0,202.0,304.0,1.0,64.0,212.0,100.0,69.0,212.0,100.0,888.0,NaN,NaN,NaN,NaN,3.0,2.0,NaN,NaN,2.0,2.0,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,5.0,5.0,NaN,5.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',1.0,2.0,NaN,NaN,2.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',5.0,11011.0,28.781560,1.0,28.781560,NaN,NaN,NaN,NaN,9.0,NaN,108.060903,1.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,7.0,1.0,52.0,4.0,68.0,173.0,7484.0,2509.0,3.0,2.0,1.0,4.0,1.0,1.0,2.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,7.000000e+00,17.0,7.000000e+00,29.0,29.0,13.0,5.397605e-79,5.397605e-79,1.000000e+00,1.000000e+00,24.0,78.0,2.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79,1.0,35.0,5.397605e-79,2876.0,493.0,1.0,5.397605e-79,60.0,60.0,2800.0,2800.0,168.0,5.397605e-79,5.397605e-79,5.397605e-79,168.0,5.397605e-79,168.0,5.397605e-79,5.397605e-79,5.397605e-79,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,4.0,2.0,2.0,NaN,NaN,2.0
2,1.0,1.0,b'02012015',b'02',b'01',b'2015',1200.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,2.0,1.000000e+00,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,15.0,88.0,88.0,1.0,2.0,2.0,1.0,3.0,NaN,1.0,1.0,1.0,7.0,2.0,1.0,2.0,NaN,2.0,1.0,2.0,1.0,2.0,2.0,3.0,NaN,2.0,2.0,4.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,99.0,2.0,158.0,511.0,NaN,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',5.0,11011.0,28.781560,2.0,57.563120,NaN,NaN,NaN,NaN,1.0,0.614125,255.264797,2.0,9.0,1.0,1.0,2.0,NaN,1.0,1.0,3.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,11.0,2.0,71.0,6.0,71.0,180.0,7167.0,2204.0,2.0,1.0,1.0,2.0,9.0,9.0,9.0,9.0,9.000000e+02,9.0,9.990000e+04,9.0,NaN,NaN,NaN,NaN,NaN,NaN,2.000000e+00,4.000000e+00,5.397605e-79,5.397605e-79,NaN,NaN,9.0,9.0,1.0,1.0,1.000000e+00,1.000000e+00,9.0,NaN,NaN,2173.0,373.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,NaN
3,1.0,1.0,b'01142015',b'01',b'14',b'2015',1100.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,3.0,1.000000e+00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,30.0,30.0,30.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,1.0,2.0,1.0,1.0,2.0,3.0,NaN,2.0,1.0,4.0,1.0,2.0,NaN,1.0,2.0,8.0,1.0,8.0,2.0,180.0,507.0,NaN,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,555.0,101.0,555.0,301.0,301.0,201.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,1.0,1.0,1.0,8.0,1.0,1.0,777777.0,5.0,1.0,9.0,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2.0,1.0,1.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',4.0,7.0,NaN,NaN,NaN,97.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',3.0,11011.0,28.781560,3.0,86.344681,NaN,NaN,NaN,NaN,1.0,0.614125,341.384853,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,3.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,9.0,1.0,63.0,5.0,67.0,170.0,8165.0,2819.0,3.0,2.0,2.0,2.0,5.0,4.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,5.397605e-79,100.0,5.397605e-79,3.0,3.0,14.0,5.397605e-79,5.397605e-79,1.000000e+00,1.000000e+00,100.0,20.0,1.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79,2.0,NaN,NaN,2469.0,423.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.397605e-79,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,3.0,3.0,2.0,2.0,4.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,9.0
4,1.0,1.0,b'01142015',b'01',b'14',b'2015',1100.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,2.0,1.000000e+00,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,20.0,88.0,30.0,1.0,1.0,2.0,1.0,3.0,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,1.0,2.0,2.0,3.0,NaN,2.0,1.0,5.0,1.0,2.0,NaN,2.0,2.0,8.0,88.0,77.0,1.0,142.0,504.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,777.0,102.0,203.0,204.0,310.0,320.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,1.0,1.0,1.0,7.0,1.0,2.0,NaN,NaN,1.0,1.0,777777.0,1.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,1.0,777.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',5.0,5.0,NaN,NaN,NaN,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',3.0,11011.0,28.781560,2.0,57.563120,NaN,NaN,NaN,NaN,9.0,NaN,258.682223,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,3.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,9.0,1.0,61.0,5.0,64.0,163.0,6441.0,2437.0,2.0,1.0,1.0,3.0,9.0,4.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,NaN,200.0,4.300000e+01,57.0,33.0,67.0,1.000000e+00,5.397605e-79,5.397605e-79,1.000000e+00,NaN,200.0,9.0,1.0,1.0,1.0,1.000000e+00,5.397605e-79,2.0,NaN,NaN,2543.0,436.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.397605e-79,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,3.0,3.0,2.0,2.0,4.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1.0,3.0,b'03162015',b'03',b'16',b'2015',1200.0,2.015001e+09,2.015001e+09,1.0,1.0,NaN,1.0,2.0,NaN,1.0,5.397605e-79,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,77.0,88.0,77.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,7.0,1.0,1.0,2.0,1.0,2.0,NaN,1.0,1.0,2.0,1.0,1.0,1.0,3.0,NaN,2.0,3.0,6.0,1.0,2.0,NaN,2.0,2.0,7.0,88.0,99.0,2.0,150.0,503.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',5.0,11091.0,31.287536,1.0,31.287536,NaN,NaN,NaN,NaN,9.0,NaN,108.441124,2.0,9.0,2.0,9.0,2.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,13.0,2.0,80.0,6.0,63.0,160.0,6804.0,2657.0,3.0,2.0,1.0,4.0,9.0,9.0,9.0,9.0,9.000000e+02,9.0,9.990000e+04,9.0,NaN,NaN,NaN,NaN,NaN,NaN,2.000000e+00,4.000000e+00,5.397605e-79,5.397605e-79,NaN,NaN,9.0,9.0,1.0,1.0,1.000000e+00,1.000000e+00,9.0,NaN,NaN,1470.0,252.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,NaN
996,1.0,3.0,b'03262015',b'03',b'26',b'2015',1200.0,2.015001e+09,2.015001e+09,1.0,1.0,NaN,1.0,2.0,NaN,2.0,1.000000e+00,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,15.0,5.0,2.0,1.0,1.0,2.0,1.0,3.0,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,1.0,2.0,2.0,2.0,9.0,2.0,3.0,NaN,2.0,9.0,5.0,9.0,2.0,NaN,1.0,2.0,9.0,88.0,99.0,1.0,9999.0,9999.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',2.0,11091.0,31.287536,2.0,62.575072,NaN,NaN,NaN,NaN,1.0,0.614125,325.255846,1.0,9.0,1.0,1.0,1.0,2.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,14.0,3.0,64.0,5.0,NaN,NaN,NaN,NaN,NaN,9.0,1.0,3.0,9.0,9.0,9.0,9.0,9.000000e+02,9.0,9.990000e+04,9.0,NaN,NaN,NaN,NaN,NaN,NaN,2.000000e+00,4.000000e+00,5.397605e-79,5.397605e-79,NaN,NaN,9.0,9.0,1.0,1.0,1.000000e+00,1.000000e+00,9.0,NaN,NaN,99900.0,99900.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,3.0,3.0,4.0,9.0,9.0,9.0,9.0,NaN
997,1.0,3.0,b'03032015',b'03',b'03',b'2015',1200.0,2.015001e+09,2.015001e+09,1.0,1.0,NaN,1.0,2.0,NaN,3.0,1.000000e+00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,4.0,15.0,4.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,1.0,2.0,1.0,1.0,39.0,2.0,2.0,4.0,1.0,1.0,2.0,1.0,2.0,7.0,2.0,6.0,1.0,9999.0,505.0,NaN,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,3.0,NaN,7.0,3.0,888.0,NaN,NaN,NaN,555.0,101.0,101.0,101.0,306.0,101.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',1.0,11092.0,46.972552,1.5,70.458829,NaN,NaN,NaN,NaN,1.0,0.614125,356.647610,1.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,3.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,9.0,1.0,61.0,5.0,65.0,165.0,NaN,NaN,NaN,9.0,3.0,2.0,4.0,3.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,5.397605e-79,100.0,1.000000e+02,100.0,20.0,100.0,5.397605e-79,5.397605e-79,1.000000e+00,1.000000e+00,100.0,320.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,9.0,NaN,NaN,2543.0,436.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,NaN,NaN,NaN
998,1.0,3.0,b'03032015',b'03',b'03',b'2015',1100.0,2.015001e+09,2.015001e+09,1.0,1.0,NaN,1.0,2.0,NaN,1.0,5.397605e-79,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,77.0,88.0,88.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,1.0,2.0,1.0,2.0,2.0,3.0,NaN,2.0,3.0,2.0,1.0,2.0,NaN,2.0,2.0,8.0,88.0,77.0,2.0,165.0,504.0,NaN,2.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,555.0,777.0,777.0,777.0,777.0,777.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,230.0,1.0,1.0,3.0,7.0,1.0,1.0,777777.0,1.0,1.0,2.0,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',5.0,5.0,NaN,NaN,NaN,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',5.0,11091.0,31.287536,1.0,31.287536,NaN,NaN,NaN,NaN,9.0,NaN,329.162164,2.0,9.0,2.0,1.0,1.0,2.0,1.0,1.0,3.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,13.0,2.0,80.0,6.0,64.0,163.0,7484.0,2832.0,3.0,2.0,1.0,1.0,9.0,4.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,5.397605e-79,NaN,NaN,NaN,NaN,NaN,1.000000e+00,4.000000e+00,5.397605e-79,5.397605e-79,NaN,NaN,9.0,9.0,1.0,1.0,1.000000e+00,1.000000e+00,2.0,NaN,NaN,1655.0,284.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.000000e+03,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,3.0,3.0,2.0,1.0,3.0,2.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,2.0
999,1.0,3.0,b'03252015',b'03',b'25',b'2015',1100.0,2.015001e+09,2.015001e+09,1.0,1.0,NaN,1.0,2.0,NaN,1.0,5.397605e-79,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,88.0,2.0,88.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,1.0,1.0,1.0,1.0,29.0,2.0,3.0,4.0,1.0,2.0,NaN,1.0,2.0,1.0,88.0,4.0,1.0,152.0,504.0,NaN,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,203.0,102.0,201.0,101.0,203.0,102.0,1.0,18.0,202.0,20.0,88.0,NaN,NaN,888.0,2.0,2.0,3.0,8.0,1.0,1.0,92014.0,8.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,1.0,403.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,1.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',5.0,4.0,1.0,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',2.0,11091.0,31.287536,1.0,31.287536,NaN,NaN,NaN,NaN,1.0,0.614125,282.842887,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,8.0,2.0,5.0,3.0,9.0,1.0,64.0,5.0,64.0,163.0,6895.0,2609.0,3.0,2.0,1.0,2.0,2.0,4.0,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,4.300000e+01,200.0,1.400000e+01,100.0,43.0,200.0,5.397605e-79,5.397605e-79,1.000000e+00,1.000000e+00,243.0,357.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79,1.0,50.0,5.397605e-79,2432.0,417.0,2.0,5.397605e-79,20.0,NaN,467.0,NaN,9.0,5.397605e-79,5.397605e-79,5.397605e-79,18.0,5.397605e-79,18.0,9.000000e+00,5.397605e-79,9.000000e+00,3.0,2.0,2.0,2.0,2.0,2.0,4.0,2.0,2.0,2.0,3.0,1.0,1.0,NaN,NaN,2.0

###Identificación de caracteristicas generales del dataset

In [ ]:
df.shape

(1000, 330)

In [ ]:
df.isnull().sum()

_STATE        0
FMONTH        0
IDATE         0
IMONTH        0
IDAY          0
           ...
_RFSEAT2      0
_RFSEAT3      0
_FLSHOT6    510
_PNEUMO2    510
_AIDTST3     99
Length: 330, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Columns: 330 entries, _STATE to _AIDTST3
dtypes: float64(323), object(7)
memory usage: 2.5+ MB

#Seleccionar columnas a trabajar

| Atributo | Tipo de datos | Naturaleza | Descripción |
| --- | --- | --- | --- |
|PHYSHLTH|	Numerico | Categorica(Nominal)-Discreta |Su salud física, incluyendo enfermedades físicas y lesiones ¿Cuántos días durante los últimos 30 días su salud un fue buena?	|
|MENTHLTH|	Numerico |Categorica(Nominal)-Discreta | Su salud mental. Que incluye estrés, depresión y problemas con las emociones, ¿Cuantos días durante los últimos 30 días su salud mental no fue buena?|
|BPHIGH4|	Numerico |Categorica(Nominal) | Diagnóstico de tensión arterial alta/hipertensión|
|TOLDHI2|	Numerico | Categorica(Nominal) |Diagnóstico de colesterol alto en la sangre|
|CVDINFR4|	Numerico |Categorica(Nominal) | Diagnóstico ataque al corazón|
|CVDCRHD4|	Numerico |Categorica(Nominal) | Diagnóstico algina de pecho o enfermedad coronaria|
|CVDSTRK3|	Numerico |Categorica(Nominal) | Diagnóstico de derrame cerebral|
|SEX|	Numerico | Categorica(Nominal) |Sexo del encuestado|
|WEIGHT2|	Numerico |Continua | Peso del encuestado|
|HEIGHT3|	Numerico |Continua | Altura del encuestado|
|SMOKE100|	Numerico |Categorica(Nominal) | ¿Ha fumado al menos 100 cigarrillos en toda su vida? (5 paquetes = 100 cigarrillos)|
|USENOW3|	Numerico |Categorica(Nominal) | Uso de productos de tabaco sin humo|
|ALCDAY5|	Numerico |Categorica(Nominal)-Continua | Días en los últimos 30 días que consumió bebidas alcohólicas	|
|FRUITJU1|	Numerico |Categorica(Nominal)-Continua | Durante los últimos 30 días ¿Cuántas veces bebió jugos de frutas 100% puros?	|
|FRUIT1|	Numerico |Categorica(Nominal)-Continua | En los últimos 30 días, sin contar jugos ¿Cuántas veces consumió fruta?|
|FVBEANS|	Numerico |Categorica(Nominal)-Continua | En el último mes ¿Cuántas veces consumió frijoles o lentejas?	|
|FVGREEN|	Numerico |Categorica(Nominal)-Continua | En el último mes ¿Cuántas veces consumiste verduras de color verde oscuro?	|
|FVORANG|	Numerico | Categorica(Nominal)-Continua |En el último mes ¿Cuántas veces comiste vegetales de color naranja?|
|VEGETAB1|	Numerico |Categorica(Nominal)-Continua | En el último mes ¿Cuántas veces consumiste otras verduras?	|
|EXERANY2|	Numerico |Categorica(Nominal) | ¿Durante el último mes participo en alguna actividad para hacer ejercicio?	|
|PREDÍAB1|	Numerico | Categorica(Nominal) |Diagnóstico de prediabetes	|

##Preparación de los datos

In [ ]:
# o seleccionar las candidatas
df = df[['PHYSHLTH','MENTHLTH','BPHIGH4','TOLDHI2','CVDINFR4','CVDCRHD4',
         'CVDSTRK3','SEX','WEIGHT2','HEIGHT3','SMOKE100','USENOW3','ALCDAY5',
         'FRUITJU1','FRUIT1','FVBEANS','FVGREEN','FVORANG','VEGETAB1',
         'EXERANY2','PREDIAB1']]
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1
0,15.0,18.0,1.0,1.0,2.0,2.0,2.0,2.0,280.0,510.0,1.0,3.0,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2.0,3.0
1,88.0,88.0,3.0,2.0,2.0,2.0,2.0,2.0,165.0,508.0,1.0,3.0,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1.0,3.0
2,15.0,88.0,3.0,1.0,7.0,2.0,1.0,2.0,158.0,511.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
3,30.0,30.0,1.0,1.0,2.0,2.0,2.0,2.0,180.0,507.0,2.0,3.0,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2.0,3.0
4,20.0,88.0,3.0,2.0,2.0,2.0,2.0,2.0,142.0,504.0,2.0,3.0,888.0,777.0,102.0,203.0,204.0,310.0,320.0,2.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,77.0,88.0,1.0,1.0,1.0,2.0,1.0,2.0,150.0,503.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
996,15.0,5.0,3.0,2.0,2.0,2.0,2.0,2.0,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
997,4.0,15.0,1.0,1.0,2.0,2.0,2.0,2.0,9999.0,505.0,1.0,3.0,888.0,555.0,101.0,101.0,101.0,306.0,101.0,NaN,NaN
998,77.0,88.0,1.0,2.0,2.0,2.0,2.0,2.0,165.0,504.0,2.0,3.0,888.0,555.0,777.0,777.0,777.0,777.0,777.0,2.0,3.0
999,88.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,152.0,504.0,2.0,3.0,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1.0,NaN

In [ ]:
#Preparacion atributo PHYSHLTH

# Eliminar filas que generan ruido
df=df[df['PHYSHLTH'] != 77.0]
df=df[df['PHYSHLTH'] != 99.0]

#Reemplazar nulos con el valor promedio
df['PHYSHLTH'] = df['PHYSHLTH'].fillna((df['PHYSHLTH'].mean()))

# Reemplazar los valores predefinidos del dataset de 88(ninguna) a cero
ValorNinguno = lambda x: 0 if (x==88.0) else x

#Almacenar los cambios en el nuevo atributo SaludFisica
df['SaludFisica'] = df['PHYSHLTH'].apply(ValorNinguno)

# Normalización: (valor-min)/(max-min)
min_veces=0
max_veces=30
NumVeces = lambda x: (x - min_veces) / (max_veces - min_veces)

#Almacenar los cambios en el nuevo atributo SaludFisica
df['SaludFisica'] = df['SaludFisica'].apply(NumVeces)
df

In [ ]:
#Preparacion atributo MENTHLTH

# Eliminar filas que generan ruido
df=df[df['MENTHLTH'] != 77.0]
df=df[df['MENTHLTH'] != 99.0]

#Reemplazar nulos con el valor promedio
df['MENTHLTH'] = df['MENTHLTH'].fillna((df['MENTHLTH'].mean()))

# Reemplazar los valores predefinidos del dataset de 88(ninguna) a cero
ValorNinguno = lambda x: 0 if (x==88.0) else x

#Almacenar los cambios en el nuevo atributo SaludMental
df['SaludMental'] = df['MENTHLTH'].apply(ValorNinguno)

# Normalización: (valor-min)/(max-min)
min_veces=0
max_veces=30
NumVeces = lambda x: (x - min_veces) / (max_veces - min_veces)

#Almacenar los cambios en el nuevo atributo SaludMental
df['SaludMental'] = df['SaludMental'].apply(NumVeces)
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental
0,15.0,18.0,1.0,1.0,2.0,2.0,2.0,2.0,280.0,510.0,1.0,3.0,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2.0,3.0,0.500000,0.600000
1,88.0,88.0,3.0,2.0,2.0,2.0,2.0,2.0,165.0,508.0,1.0,3.0,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1.0,3.0,0.000000,0.000000
2,15.0,88.0,3.0,1.0,7.0,2.0,1.0,2.0,158.0,511.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.500000,0.000000
3,30.0,30.0,1.0,1.0,2.0,2.0,2.0,2.0,180.0,507.0,2.0,3.0,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2.0,3.0,1.000000,1.000000
4,20.0,88.0,3.0,2.0,2.0,2.0,2.0,2.0,142.0,504.0,2.0,3.0,888.0,777.0,102.0,203.0,204.0,310.0,320.0,2.0,3.0,0.666667,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,88.0,88.0,3.0,2.0,2.0,2.0,2.0,1.0,250.0,510.0,1.0,3.0,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1.0,3.0,0.000000,0.000000
994,88.0,88.0,3.0,2.0,2.0,2.0,2.0,2.0,163.0,506.0,2.0,3.0,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1.0,1.0,0.000000,0.000000
996,15.0,5.0,3.0,2.0,2.0,2.0,2.0,2.0,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.500000,0.166667
997,4.0,15.0,1.0,1.0,2.0,2.0,2.0,2.0,9999.0,505.0,1.0,3.0,888.0,555.0,101.0,101.0,101.0,306.0,101.0,NaN,NaN,0.133333,0.500000
999,88.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,152.0,504.0,2.0,3.0,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1.0,NaN,0.000000,0.066667

In [ ]:
#Preparacion atributo BPHIGH4

# Eliminar filas que generan ruido
df=df[df['BPHIGH4'] != 7.0]
df=df[df['BPHIGH4'] != 9.0]

#Reemplazar nulos con el valor promedio
df['BPHIGH4'] = df['BPHIGH4'].fillna((df['BPHIGH4'].mean()))
df['BPHIGH4'] = df['BPHIGH4'].astype(int)
#Almacenar los cambios en el nuevo atributo DiagHipertension
df['DiagHipertension'] = df['BPHIGH4'].apply(ValorNinguno)

# Crear columnas dummy (one-hot-encoding)
# Generar columnas
df = pd.concat([df, pd.get_dummies(df['DiagHipertension'], prefix='Hip')], axis=1)
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental,DiagHipertension,Hip_1,Hip_2,Hip_3,Hip_4
0,15.0,18.0,1,1.0,2.0,2.0,2.0,2.0,280.0,510.0,1.0,3.0,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2.0,3.0,0.500000,0.600000,1,1,0,0,0
1,88.0,88.0,3,2.0,2.0,2.0,2.0,2.0,165.0,508.0,1.0,3.0,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0
2,15.0,88.0,3,1.0,7.0,2.0,1.0,2.0,158.0,511.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.500000,0.000000,3,0,0,1,0
3,30.0,30.0,1,1.0,2.0,2.0,2.0,2.0,180.0,507.0,2.0,3.0,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2.0,3.0,1.000000,1.000000,1,1,0,0,0
4,20.0,88.0,3,2.0,2.0,2.0,2.0,2.0,142.0,504.0,2.0,3.0,888.0,777.0,102.0,203.0,204.0,310.0,320.0,2.0,3.0,0.666667,0.000000,3,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,88.0,88.0,3,2.0,2.0,2.0,2.0,1.0,250.0,510.0,1.0,3.0,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0
994,88.0,88.0,3,2.0,2.0,2.0,2.0,2.0,163.0,506.0,2.0,3.0,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1.0,1.0,0.000000,0.000000,3,0,0,1,0
996,15.0,5.0,3,2.0,2.0,2.0,2.0,2.0,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.500000,0.166667,3,0,0,1,0
997,4.0,15.0,1,1.0,2.0,2.0,2.0,2.0,9999.0,505.0,1.0,3.0,888.0,555.0,101.0,101.0,101.0,306.0,101.0,NaN,NaN,0.133333,0.500000,1,1,0,0,0
999,88.0,2.0,1,1.0,2.0,2.0,2.0,2.0,152.0,504.0,2.0,3.0,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1.0,NaN,0.000000,0.066667,1,1,0,0,0

In [ ]:
#Preparacion atributo TOLDHI2

# Eliminar filas que generan ruido
df=df[df['TOLDHI2'] != 7.0]
df=df[df['TOLDHI2'] != 9.0]

#Reemplazar nulos con el valor promedio
df['TOLDHI2'] = df['TOLDHI2'].fillna((df['TOLDHI2'].mean()))
df['TOLDHI2'] = df['TOLDHI2'].astype(int)

# Reemplazar los valores predefinidos del dataset de 88(ninguna) a cero
ValorNinguno = lambda x: 0 if (x==88.0) else x

#Almacenar los cambios en el nuevo atributo DiagColesterol
df['DiagColesterol'] = df['TOLDHI2'].apply(ValorNinguno)

# Normalización: 1 y -1
convertir_diag_colesterol = lambda x: 1 if (x==1) else -1
df['DiagColesterol'] = df['DiagColesterol'].apply(convertir_diag_colesterol)
df

#Almacenar los cambios en el nuevo atributo DiagColesterol
df['DiagColesterol'] = df['DiagColesterol'].apply(convertir_diag_colesterol)
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental,DiagHipertension,Hip_1,Hip_2,Hip_3,Hip_4,DiagColesterol
0,15.0,18.0,1,1,2.0,2.0,2.0,2.0,280.0,510.0,1.0,3.0,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2.0,3.0,0.500000,0.600000,1,1,0,0,0,1
1,88.0,88.0,3,2,2.0,2.0,2.0,2.0,165.0,508.0,1.0,3.0,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1
2,15.0,88.0,3,1,7.0,2.0,1.0,2.0,158.0,511.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.500000,0.000000,3,0,0,1,0,1
3,30.0,30.0,1,1,2.0,2.0,2.0,2.0,180.0,507.0,2.0,3.0,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2.0,3.0,1.000000,1.000000,1,1,0,0,0,1
4,20.0,88.0,3,2,2.0,2.0,2.0,2.0,142.0,504.0,2.0,3.0,888.0,777.0,102.0,203.0,204.0,310.0,320.0,2.0,3.0,0.666667,0.000000,3,0,0,1,0,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,88.0,88.0,3,2,2.0,2.0,2.0,1.0,250.0,510.0,1.0,3.0,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1
994,88.0,88.0,3,2,2.0,2.0,2.0,2.0,163.0,506.0,2.0,3.0,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1.0,1.0,0.000000,0.000000,3,0,0,1,0,-1
996,15.0,5.0,3,2,2.0,2.0,2.0,2.0,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.500000,0.166667,3,0,0,1,0,-1
997,4.0,15.0,1,1,2.0,2.0,2.0,2.0,9999.0,505.0,1.0,3.0,888.0,555.0,101.0,101.0,101.0,306.0,101.0,NaN,NaN,0.133333,0.500000,1,1,0,0,0,1
999,88.0,2.0,1,1,2.0,2.0,2.0,2.0,152.0,504.0,2.0,3.0,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1.0,NaN,0.000000,0.066667,1,1,0,0,0,1

In [ ]:
#Preparacion atributo CVDINFR4

# Eliminar filas que generan ruido
df=df[df['CVDINFR4'] != 7.0]
df=df[df['CVDINFR4'] != 9.0]

#Reemplazar nulos con el valor promedio
df['CVDINFR4'] = df['CVDINFR4'].fillna((df['CVDINFR4'].mean()))
df['CVDINFR4'] = df['CVDINFR4'].astype(int)

# Reemplazar los valores predefinidos del dataset de 88(ninguna) a cero
ValorNinguno = lambda x: 0 if (x==88.0) else x

#Almacenar los cambios en el nuevo atributo DiagAtaqCorazon
df['DiagAtaqCorazon'] = df['CVDINFR4'].apply(ValorNinguno)

# Normalización: 1 y -1
convertir_diag_ataq_corazon = lambda x: 1 if (x==1) else -1
df['DiagAtaqCorazon'] = df['DiagAtaqCorazon'].apply(convertir_diag_ataq_corazon)
df

#Almacenar los cambios en el nuevo atributo DiagAtaqCorazon
df['DiagAtaqCorazon'] = df['DiagAtaqCorazon'].apply(convertir_diag_ataq_corazon)
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental,DiagHipertension,Hip_1,Hip_2,Hip_3,Hip_4,DiagColesterol,DiagAtaqCorazon
0,15.0,18.0,1,1,2,2.0,2.0,2.0,280.0,510.0,1.0,3.0,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2.0,3.0,0.500000,0.600000,1,1,0,0,0,1,-1
1,88.0,88.0,3,2,2,2.0,2.0,2.0,165.0,508.0,1.0,3.0,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1
3,30.0,30.0,1,1,2,2.0,2.0,2.0,180.0,507.0,2.0,3.0,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2.0,3.0,1.000000,1.000000,1,1,0,0,0,1,-1
4,20.0,88.0,3,2,2,2.0,2.0,2.0,142.0,504.0,2.0,3.0,888.0,777.0,102.0,203.0,204.0,310.0,320.0,2.0,3.0,0.666667,0.000000,3,0,0,1,0,-1,-1
5,88.0,88.0,1,2,2,2.0,2.0,2.0,145.0,502.0,2.0,3.0,888.0,101.0,101.0,102.0,101.0,102.0,101.0,1.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,88.0,88.0,3,2,2,2.0,2.0,1.0,250.0,510.0,1.0,3.0,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1
994,88.0,88.0,3,2,2,2.0,2.0,2.0,163.0,506.0,2.0,3.0,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1.0,1.0,0.000000,0.000000,3,0,0,1,0,-1,-1
996,15.0,5.0,3,2,2,2.0,2.0,2.0,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.500000,0.166667,3,0,0,1,0,-1,-1
997,4.0,15.0,1,1,2,2.0,2.0,2.0,9999.0,505.0,1.0,3.0,888.0,555.0,101.0,101.0,101.0,306.0,101.0,NaN,NaN,0.133333,0.500000,1,1,0,0,0,1,-1
999,88.0,2.0,1,1,2,2.0,2.0,2.0,152.0,504.0,2.0,3.0,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1.0,NaN,0.000000,0.066667,1,1,0,0,0,1,-1

In [ ]:
#Preparacion atributo CVDCRHD4

# Eliminar filas que generan ruido
df=df[df['CVDCRHD4'] != 7.0]
df=df[df['CVDCRHD4'] != 9.0]

#Reemplazar nulos con el valor promedio
df['CVDCRHD4'] = df['CVDCRHD4'].fillna((df['CVDCRHD4'].mean()))
df['CVDCRHD4'] = df['CVDCRHD4'].astype(int)

# Reemplazar los valores predefinidos del dataset de 88(ninguna) a cero
ValorNinguno = lambda x: 0 if (x==88.0) else x

#Almacenar los cambios en el nuevo atributo DiagEnfCorazon
df['DiagEnfCorazon'] = df['CVDCRHD4'].apply(ValorNinguno)

# Normalización: 1 y -1
convertir_diag_enf_corazon = lambda x: 1 if (x==1) else -1
df['DiagEnfCorazon'] = df['DiagEnfCorazon'].apply(convertir_diag_enf_corazon)
df

#Almacenar los cambios en el nuevo atributo DiagEnfCorazon
df['DiagEnfCorazon'] = df['DiagEnfCorazon'].apply(convertir_diag_enf_corazon)
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental,DiagHipertension,Hip_1,Hip_2,Hip_3,Hip_4,DiagColesterol,DiagAtaqCorazon,DiagEnfCorazon
0,15.0,18.0,1,1,2,2,2.0,2.0,280.0,510.0,1.0,3.0,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2.0,3.0,0.500000,0.600000,1,1,0,0,0,1,-1,-1
1,88.0,88.0,3,2,2,2,2.0,2.0,165.0,508.0,1.0,3.0,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1
3,30.0,30.0,1,1,2,2,2.0,2.0,180.0,507.0,2.0,3.0,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2.0,3.0,1.000000,1.000000,1,1,0,0,0,1,-1,-1
4,20.0,88.0,3,2,2,2,2.0,2.0,142.0,504.0,2.0,3.0,888.0,777.0,102.0,203.0,204.0,310.0,320.0,2.0,3.0,0.666667,0.000000,3,0,0,1,0,-1,-1,-1
5,88.0,88.0,1,2,2,2,2.0,2.0,145.0,502.0,2.0,3.0,888.0,101.0,101.0,102.0,101.0,102.0,101.0,1.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,88.0,88.0,3,2,2,2,2.0,1.0,250.0,510.0,1.0,3.0,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1
994,88.0,88.0,3,2,2,2,2.0,2.0,163.0,506.0,2.0,3.0,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1.0,1.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1
996,15.0,5.0,3,2,2,2,2.0,2.0,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.500000,0.166667,3,0,0,1,0,-1,-1,-1
997,4.0,15.0,1,1,2,2,2.0,2.0,9999.0,505.0,1.0,3.0,888.0,555.0,101.0,101.0,101.0,306.0,101.0,NaN,NaN,0.133333,0.500000,1,1,0,0,0,1,-1,-1
999,88.0,2.0,1,1,2,2,2.0,2.0,152.0,504.0,2.0,3.0,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1.0,NaN,0.000000,0.066667,1,1,0,0,0,1,-1,-1

In [ ]:
#Preparacion atributo CVDSTRK3

# Eliminar filas que generan ruido
df=df[df['CVDSTRK3'] != 7.0]
df=df[df['CVDSTRK3'] != 9.0]

#Reemplazar nulos con el valor promedio
df['CVDSTRK3'] = df['CVDSTRK3'].fillna((df['CVDSTRK3'].mean()))
df['CVDSTRK3'] = df['CVDSTRK3'].astype(int)

# Reemplazar los valores predefinidos del dataset de 88(ninguna) a cero
ValorNinguno = lambda x: 0 if (x==88.0) else x

#Almacenar los cambios en el nuevo atributo DiagDerrCerebral
df['DiagDerrCerebral'] = df['CVDSTRK3'].apply(ValorNinguno)

# Normalización: 1 y -1
convertir_diag_derrame = lambda x: 1 if (x==1) else -1
df['DiagDerrCerebral'] = df['DiagDerrCerebral'].apply(convertir_diag_derrame)
df

#Almacenar los cambios en el nuevo atributo DiagDerrCerebral
df['DiagDerrCerebral'] = df['DiagDerrCerebral'].apply(convertir_diag_derrame)
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental,DiagHipertension,Hip_1,Hip_2,Hip_3,Hip_4,DiagColesterol,DiagAtaqCorazon,DiagEnfCorazon,DiagDerrCerebral
0,15.0,18.0,1,1,2,2,2,2.0,280.0,510.0,1.0,3.0,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2.0,3.0,0.500000,0.600000,1,1,0,0,0,1,-1,-1,-1
1,88.0,88.0,3,2,2,2,2,2.0,165.0,508.0,1.0,3.0,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1
3,30.0,30.0,1,1,2,2,2,2.0,180.0,507.0,2.0,3.0,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2.0,3.0,1.000000,1.000000,1,1,0,0,0,1,-1,-1,-1
4,20.0,88.0,3,2,2,2,2,2.0,142.0,504.0,2.0,3.0,888.0,777.0,102.0,203.0,204.0,310.0,320.0,2.0,3.0,0.666667,0.000000,3,0,0,1,0,-1,-1,-1,-1
5,88.0,88.0,1,2,2,2,2,2.0,145.0,502.0,2.0,3.0,888.0,101.0,101.0,102.0,101.0,102.0,101.0,1.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,88.0,88.0,3,2,2,2,2,1.0,250.0,510.0,1.0,3.0,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1
994,88.0,88.0,3,2,2,2,2,2.0,163.0,506.0,2.0,3.0,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1.0,1.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1
996,15.0,5.0,3,2,2,2,2,2.0,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.500000,0.166667,3,0,0,1,0,-1,-1,-1,-1
997,4.0,15.0,1,1,2,2,2,2.0,9999.0,505.0,1.0,3.0,888.0,555.0,101.0,101.0,101.0,306.0,101.0,NaN,NaN,0.133333,0.500000,1,1,0,0,0,1,-1,-1,-1
999,88.0,2.0,1,1,2,2,2,2.0,152.0,504.0,2.0,3.0,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1.0,NaN,0.000000,0.066667,1,1,0,0,0,1,-1,-1,-1

In [ ]:
#Preparacion atributo SEX

#Almacenar los cambios en el nuevo atributo Sexo
df['Sexo'] = df['SEX'].apply(ValorNinguno)

# Normalización: 1 y -1
convertir_sexo = lambda x: 1 if (x==1) else -1
df['Sexo'] = df['Sexo'].apply(convertir_sexo)
df

#Almacenar los cambios en el nuevo atributo Sexo
df['Sexo'] = df['Sexo'].apply(convertir_sexo)
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental,DiagHipertension,Hip_1,Hip_2,Hip_3,Hip_4,DiagColesterol,DiagAtaqCorazon,DiagEnfCorazon,DiagDerrCerebral,Sexo
0,15.0,18.0,1,1,2,2,2,2.0,280.0,510.0,1.0,3.0,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2.0,3.0,0.500000,0.600000,1,1,0,0,0,1,-1,-1,-1,-1
1,88.0,88.0,3,2,2,2,2,2.0,165.0,508.0,1.0,3.0,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1
3,30.0,30.0,1,1,2,2,2,2.0,180.0,507.0,2.0,3.0,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2.0,3.0,1.000000,1.000000,1,1,0,0,0,1,-1,-1,-1,-1
4,20.0,88.0,3,2,2,2,2,2.0,142.0,504.0,2.0,3.0,888.0,777.0,102.0,203.0,204.0,310.0,320.0,2.0,3.0,0.666667,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1
5,88.0,88.0,1,2,2,2,2,2.0,145.0,502.0,2.0,3.0,888.0,101.0,101.0,102.0,101.0,102.0,101.0,1.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,88.0,88.0,3,2,2,2,2,1.0,250.0,510.0,1.0,3.0,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,1
994,88.0,88.0,3,2,2,2,2,2.0,163.0,506.0,2.0,3.0,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1.0,1.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1
996,15.0,5.0,3,2,2,2,2,2.0,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.500000,0.166667,3,0,0,1,0,-1,-1,-1,-1,-1
997,4.0,15.0,1,1,2,2,2,2.0,9999.0,505.0,1.0,3.0,888.0,555.0,101.0,101.0,101.0,306.0,101.0,NaN,NaN,0.133333,0.500000,1,1,0,0,0,1,-1,-1,-1,-1
999,88.0,2.0,1,1,2,2,2,2.0,152.0,504.0,2.0,3.0,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1.0,NaN,0.000000,0.066667,1,1,0,0,0,1,-1,-1,-1,-1

In [ ]:
#Preparacion atributo HEIGHT3

# Eliminar filas que generan ruido
df=df[df['HEIGHT3'] != 7777.0]
df=df[df['HEIGHT3'] != 9999.0]

#Reemplazar nulos con el valor promedio
df['HEIGHT3'] = df['HEIGHT3'].fillna((df['HEIGHT3'].mean()))

# Reemplazar los valores predefinidos del dataset de 88(ninguna) a cero
ValorNinguno = lambda x: 0 if (x==88888.0) else x
QuitarMiles = lambda y: df['HEIGHT3']-9000.0 if(y>=9000.0) else y
#Almacenar los cambios en el nuevo atributo Altura
df['Altura'] = df['HEIGHT3'].apply(ValorNinguno)
df['Altura'] = df['Altura'].apply(QuitarMiles)

#Convertir de metros a cm
df['Altura']=df['Altura']/100
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental,DiagHipertension,Hip_1,Hip_2,Hip_3,Hip_4,DiagColesterol,DiagAtaqCorazon,DiagEnfCorazon,DiagDerrCerebral,Sexo,Altura
0,15.0,18.0,1,1,2,2,2,2.0,280.0,510.0,1.0,3.0,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2.0,3.0,0.500000,0.600000,1,1,0,0,0,1,-1,-1,-1,-1,5.10
1,88.0,88.0,3,2,2,2,2,2.0,165.0,508.0,1.0,3.0,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,5.08
3,30.0,30.0,1,1,2,2,2,2.0,180.0,507.0,2.0,3.0,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2.0,3.0,1.000000,1.000000,1,1,0,0,0,1,-1,-1,-1,-1,5.07
4,20.0,88.0,3,2,2,2,2,2.0,142.0,504.0,2.0,3.0,888.0,777.0,102.0,203.0,204.0,310.0,320.0,2.0,3.0,0.666667,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,5.04
5,88.0,88.0,1,2,2,2,2,2.0,145.0,502.0,2.0,3.0,888.0,101.0,101.0,102.0,101.0,102.0,101.0,1.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,5.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,88.0,88.0,1,2,2,2,2,2.0,140.0,502.0,2.0,3.0,230.0,330.0,202.0,330.0,203.0,202.0,330.0,2.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,5.02
993,88.0,88.0,3,2,2,2,2,1.0,250.0,510.0,1.0,3.0,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,1,5.10
994,88.0,88.0,3,2,2,2,2,2.0,163.0,506.0,2.0,3.0,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1.0,1.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,5.06
997,4.0,15.0,1,1,2,2,2,2.0,9999.0,505.0,1.0,3.0,888.0,555.0,101.0,101.0,101.0,306.0,101.0,NaN,NaN,0.133333,0.500000,1,1,0,0,0,1,-1,-1,-1,-1,5.05
999,88.0,2.0,1,1,2,2,2,2.0,152.0,504.0,2.0,3.0,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1.0,NaN,0.000000,0.066667,1,1,0,0,0,1,-1,-1,-1,-1,5.04

In [ ]:
#Preparacion atributo WEIGHT2

# Eliminar filas que generan ruido
df=df[df['WEIGHT2'] != 7777.0]
df=df[df['WEIGHT2'] != 9999.0]


#Reemplazar nulos con el valor promedio
df['WEIGHT2'] = df['WEIGHT2'].fillna((df['WEIGHT2'].mean()))

# Reemplazar los valores predefinidos del dataset de 88(ninguna) a cero
ValorNinguno = lambda x: 0 if (x==88888.0) else x
QuitarMiles = lambda y: df['HEIGHT3']-9000.0 if(y>=9000.0) else y
#Almacenar los cambios en el nuevo atributo Peso
df['Peso'] = df['WEIGHT2'].apply(ValorNinguno)
df['Peso'] = df['Peso'].apply(QuitarMiles)


df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental,DiagHipertension,Hip_1,Hip_2,Hip_3,Hip_4,DiagColesterol,DiagAtaqCorazon,DiagEnfCorazon,DiagDerrCerebral,Sexo,Altura,Peso
0,15.0,18.0,1,1,2,2,2,2.0,280.0,510.0,1.0,3.0,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2.0,3.0,0.500000,0.600000,1,1,0,0,0,1,-1,-1,-1,-1,5.10,280.0
1,88.0,88.0,3,2,2,2,2,2.0,165.0,508.0,1.0,3.0,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,5.08,165.0
3,30.0,30.0,1,1,2,2,2,2.0,180.0,507.0,2.0,3.0,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2.0,3.0,1.000000,1.000000,1,1,0,0,0,1,-1,-1,-1,-1,5.07,180.0
4,20.0,88.0,3,2,2,2,2,2.0,142.0,504.0,2.0,3.0,888.0,777.0,102.0,203.0,204.0,310.0,320.0,2.0,3.0,0.666667,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,5.04,142.0
5,88.0,88.0,1,2,2,2,2,2.0,145.0,502.0,2.0,3.0,888.0,101.0,101.0,102.0,101.0,102.0,101.0,1.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,5.02,145.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2.0,88.0,1,2,2,2,2,2.0,175.0,505.0,2.0,3.0,204.0,555.0,102.0,555.0,101.0,315.0,315.0,1.0,1.0,0.066667,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,5.05,175.0
992,88.0,88.0,1,2,2,2,2,2.0,140.0,502.0,2.0,3.0,230.0,330.0,202.0,330.0,203.0,202.0,330.0,2.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,5.02,140.0
993,88.0,88.0,3,2,2,2,2,1.0,250.0,510.0,1.0,3.0,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,1,5.10,250.0
994,88.0,88.0,3,2,2,2,2,2.0,163.0,506.0,2.0,3.0,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1.0,1.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,5.06,163.0
999,88.0,2.0,1,1,2,2,2,2.0,152.0,504.0,2.0,3.0,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1.0,NaN,0.000000,0.066667,1,1,0,0,0,1,-1,-1,-1,-1,5.04,152.0

In [ ]:
#Creación atributo IMC

#Calculo Formula
#IMC = df['WEIGHT2']/(df['HEIGHT3']**2)

df['IMC'] = df['Peso']/(df['Altura']**2)
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental,DiagHipertension,Hip_1,Hip_2,Hip_3,Hip_4,DiagColesterol,DiagAtaqCorazon,DiagEnfCorazon,DiagDerrCerebral,Sexo,Altura,Peso,IMC
0,15.0,18.0,1,1,2,2,2,2.0,280.0,510.0,1.0,3.0,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2.0,3.0,0.500000,0.600000,1,1,0,0,0,1,-1,-1,-1,-1,5.10,280.0,10.765090
1,88.0,88.0,3,2,2,2,2,2.0,165.0,508.0,1.0,3.0,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,5.08,165.0,6.393763
3,30.0,30.0,1,1,2,2,2,2.0,180.0,507.0,2.0,3.0,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2.0,3.0,1.000000,1.000000,1,1,0,0,0,1,-1,-1,-1,-1,5.07,180.0,7.002556
4,20.0,88.0,3,2,2,2,2,2.0,142.0,504.0,2.0,3.0,888.0,777.0,102.0,203.0,204.0,310.0,320.0,2.0,3.0,0.666667,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,5.04,142.0,5.590199
5,88.0,88.0,1,2,2,2,2,2.0,145.0,502.0,2.0,3.0,888.0,101.0,101.0,102.0,101.0,102.0,101.0,1.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,5.02,145.0,5.753877
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2.0,88.0,1,2,2,2,2,2.0,175.0,505.0,2.0,3.0,204.0,555.0,102.0,555.0,101.0,315.0,315.0,1.0,1.0,0.066667,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,5.05,175.0,6.862072
992,88.0,88.0,1,2,2,2,2,2.0,140.0,502.0,2.0,3.0,230.0,330.0,202.0,330.0,203.0,202.0,330.0,2.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,5.02,140.0,5.555467
993,88.0,88.0,3,2,2,2,2,1.0,250.0,510.0,1.0,3.0,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,1,5.10,250.0,9.611688
994,88.0,88.0,3,2,2,2,2,2.0,163.0,506.0,2.0,3.0,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1.0,1.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,5.06,163.0,6.366292
999,88.0,2.0,1,1,2,2,2,2.0,152.0,504.0,2.0,3.0,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1.0,NaN,0.000000,0.066667,1,1,0,0,0,1,-1,-1,-1,-1,5.04,152.0,5.983875

In [ ]:
#Normalización atributo Altura(HEIGHT3)

# Normalización: (valor-min)/(max-min)
min_veces=df['Altura'].min()
max_veces=df['Altura'].max()
NumVeces = lambda x: (x - min_veces) / (max_veces - min_veces)

#Almacenar los cambios en el nuevo atributo Altura
df['Altura'] = df['Altura'].apply(NumVeces)
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental,DiagHipertension,Hip_1,Hip_2,Hip_3,Hip_4,DiagColesterol,DiagAtaqCorazon,DiagEnfCorazon,DiagDerrCerebral,Sexo,Altura,Peso,IMC
0,15.0,18.0,1,1,2,2,2,2.0,280.0,510.0,1.0,3.0,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2.0,3.0,0.500000,0.600000,1,1,0,0,0,1,-1,-1,-1,-1,0.515306,280.0,10.765090
1,88.0,88.0,3,2,2,2,2,2.0,165.0,508.0,1.0,3.0,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.505102,165.0,6.393763
3,30.0,30.0,1,1,2,2,2,2.0,180.0,507.0,2.0,3.0,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2.0,3.0,1.000000,1.000000,1,1,0,0,0,1,-1,-1,-1,-1,0.500000,180.0,7.002556
4,20.0,88.0,3,2,2,2,2,2.0,142.0,504.0,2.0,3.0,888.0,777.0,102.0,203.0,204.0,310.0,320.0,2.0,3.0,0.666667,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.484694,142.0,5.590199
5,88.0,88.0,1,2,2,2,2,2.0,145.0,502.0,2.0,3.0,888.0,101.0,101.0,102.0,101.0,102.0,101.0,1.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,145.0,5.753877
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2.0,88.0,1,2,2,2,2,2.0,175.0,505.0,2.0,3.0,204.0,555.0,102.0,555.0,101.0,315.0,315.0,1.0,1.0,0.066667,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.489796,175.0,6.862072
992,88.0,88.0,1,2,2,2,2,2.0,140.0,502.0,2.0,3.0,230.0,330.0,202.0,330.0,203.0,202.0,330.0,2.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,140.0,5.555467
993,88.0,88.0,3,2,2,2,2,1.0,250.0,510.0,1.0,3.0,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,1,0.515306,250.0,9.611688
994,88.0,88.0,3,2,2,2,2,2.0,163.0,506.0,2.0,3.0,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1.0,1.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.494898,163.0,6.366292
999,88.0,2.0,1,1,2,2,2,2.0,152.0,504.0,2.0,3.0,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1.0,NaN,0.000000,0.066667,1,1,0,0,0,1,-1,-1,-1,-1,0.484694,152.0,5.983875

In [ ]:
#Normalización atributo WEIGHT2

# Normalización: (valor-min)/(max-min)
min_veces=df['Peso'].min()
max_veces=df['Peso'].max()
NumVeces = lambda x: (x - min_veces) / (max_veces - min_veces)

#Almacenar los cambios en el nuevo atributo Peso
df['Peso'] = df['Peso'].apply(NumVeces)
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental,DiagHipertension,Hip_1,Hip_2,Hip_3,Hip_4,DiagColesterol,DiagAtaqCorazon,DiagEnfCorazon,DiagDerrCerebral,Sexo,Altura,Peso,IMC
0,15.0,18.0,1,1,2,2,2,2.0,280.0,510.0,1.0,3.0,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2.0,3.0,0.500000,0.600000,1,1,0,0,0,1,-1,-1,-1,-1,0.515306,0.617834,10.765090
1,88.0,88.0,3,2,2,2,2,2.0,165.0,508.0,1.0,3.0,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.505102,0.251592,6.393763
3,30.0,30.0,1,1,2,2,2,2.0,180.0,507.0,2.0,3.0,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2.0,3.0,1.000000,1.000000,1,1,0,0,0,1,-1,-1,-1,-1,0.500000,0.299363,7.002556
4,20.0,88.0,3,2,2,2,2,2.0,142.0,504.0,2.0,3.0,888.0,777.0,102.0,203.0,204.0,310.0,320.0,2.0,3.0,0.666667,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.484694,0.178344,5.590199
5,88.0,88.0,1,2,2,2,2,2.0,145.0,502.0,2.0,3.0,888.0,101.0,101.0,102.0,101.0,102.0,101.0,1.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.187898,5.753877
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2.0,88.0,1,2,2,2,2,2.0,175.0,505.0,2.0,3.0,204.0,555.0,102.0,555.0,101.0,315.0,315.0,1.0,1.0,0.066667,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.489796,0.283439,6.862072
992,88.0,88.0,1,2,2,2,2,2.0,140.0,502.0,2.0,3.0,230.0,330.0,202.0,330.0,203.0,202.0,330.0,2.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.171975,5.555467
993,88.0,88.0,3,2,2,2,2,1.0,250.0,510.0,1.0,3.0,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,1,0.515306,0.522293,9.611688
994,88.0,88.0,3,2,2,2,2,2.0,163.0,506.0,2.0,3.0,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1.0,1.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.494898,0.245223,6.366292
999,88.0,2.0,1,1,2,2,2,2.0,152.0,504.0,2.0,3.0,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1.0,NaN,0.000000,0.066667,1,1,0,0,0,1,-1,-1,-1,-1,0.484694,0.210191,5.983875

In [ ]:
#Normalización atributo IMC
#Eliminar datos sesgados
df=df[df['IMC'] < 138.0]
# Normalización: (valor-min)/(max-min)
min_veces=df['IMC'].min()
max_veces=df['IMC'].max()
NumVeces = lambda x: (x - min_veces) / (max_veces - min_veces)

#Almacenar los cambios en el nuevo atributo Peso
df['IMC'] = df['IMC'].apply(NumVeces)
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental,DiagHipertension,Hip_1,Hip_2,Hip_3,Hip_4,DiagColesterol,DiagAtaqCorazon,DiagEnfCorazon,DiagDerrCerebral,Sexo,Altura,Peso,IMC
0,15.0,18.0,1,1,2,2,2,2.0,280.0,510.0,1.0,3.0,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2.0,3.0,0.500000,0.600000,1,1,0,0,0,1,-1,-1,-1,-1,0.515306,0.617834,0.730997
1,88.0,88.0,3,2,2,2,2,2.0,165.0,508.0,1.0,3.0,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.505102,0.251592,0.318544
3,30.0,30.0,1,1,2,2,2,2.0,180.0,507.0,2.0,3.0,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2.0,3.0,1.000000,1.000000,1,1,0,0,0,1,-1,-1,-1,-1,0.500000,0.299363,0.375987
4,20.0,88.0,3,2,2,2,2,2.0,142.0,504.0,2.0,3.0,888.0,777.0,102.0,203.0,204.0,310.0,320.0,2.0,3.0,0.666667,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.484694,0.178344,0.242725
5,88.0,88.0,1,2,2,2,2,2.0,145.0,502.0,2.0,3.0,888.0,101.0,101.0,102.0,101.0,102.0,101.0,1.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.187898,0.258169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2.0,88.0,1,2,2,2,2,2.0,175.0,505.0,2.0,3.0,204.0,555.0,102.0,555.0,101.0,315.0,315.0,1.0,1.0,0.066667,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.489796,0.283439,0.362731
992,88.0,88.0,1,2,2,2,2,2.0,140.0,502.0,2.0,3.0,230.0,330.0,202.0,330.0,203.0,202.0,330.0,2.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.171975,0.239448
993,88.0,88.0,3,2,2,2,2,1.0,250.0,510.0,1.0,3.0,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,1,0.515306,0.522293,0.622169
994,88.0,88.0,3,2,2,2,2,2.0,163.0,506.0,2.0,3.0,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1.0,1.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.494898,0.245223,0.315953
999,88.0,2.0,1,1,2,2,2,2.0,152.0,504.0,2.0,3.0,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1.0,NaN,0.000000,0.066667,1,1,0,0,0,1,-1,-1,-1,-1,0.484694,0.210191,0.279870

In [ ]:
#Preparacion atributo SMOKE100

# Eliminar filas que generan ruido
df=df[df['SMOKE100'] != 7.0]
df=df[df['SMOKE100'] != 9.0]

#Reemplazar nulos con el valor promedio
df['SMOKE100'] = df['SMOKE100'].fillna((df['SMOKE100'].mean()))
df['SMOKE100'] = df['SMOKE100'].astype(int)

# Reemplazar los valores predefinidos del dataset de 88(ninguna) a cero
ValorNinguno = lambda x: 0 if (x==88.0) else x

#Almacenar los cambios en el nuevo atributo Fumar100
df['Fumar100'] = df['SMOKE100'].apply(ValorNinguno)

# Normalización: 1 y -1
convertir_fumar100 = lambda x: 1 if (x==1) else -1
df['Fumar100'] = df['Fumar100'].apply(convertir_fumar100)
df

#Almacenar los cambios en el nuevo atributo DiagDerrCerebral
df['Fumar100'] = df['Fumar100'].apply(convertir_fumar100)
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental,DiagHipertension,Hip_1,Hip_2,Hip_3,Hip_4,DiagColesterol,DiagAtaqCorazon,DiagEnfCorazon,DiagDerrCerebral,Sexo,Altura,Peso,IMC,Fumar100
0,15.0,18.0,1,1,2,2,2,2.0,280.0,510.0,1,3.0,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2.0,3.0,0.500000,0.600000,1,1,0,0,0,1,-1,-1,-1,-1,0.515306,0.617834,0.730997,1
1,88.0,88.0,3,2,2,2,2,2.0,165.0,508.0,1,3.0,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.505102,0.251592,0.318544,1
3,30.0,30.0,1,1,2,2,2,2.0,180.0,507.0,2,3.0,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2.0,3.0,1.000000,1.000000,1,1,0,0,0,1,-1,-1,-1,-1,0.500000,0.299363,0.375987,-1
4,20.0,88.0,3,2,2,2,2,2.0,142.0,504.0,2,3.0,888.0,777.0,102.0,203.0,204.0,310.0,320.0,2.0,3.0,0.666667,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.484694,0.178344,0.242725,-1
5,88.0,88.0,1,2,2,2,2,2.0,145.0,502.0,2,3.0,888.0,101.0,101.0,102.0,101.0,102.0,101.0,1.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.187898,0.258169,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2.0,88.0,1,2,2,2,2,2.0,175.0,505.0,2,3.0,204.0,555.0,102.0,555.0,101.0,315.0,315.0,1.0,1.0,0.066667,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.489796,0.283439,0.362731,-1
992,88.0,88.0,1,2,2,2,2,2.0,140.0,502.0,2,3.0,230.0,330.0,202.0,330.0,203.0,202.0,330.0,2.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.171975,0.239448,-1
993,88.0,88.0,3,2,2,2,2,1.0,250.0,510.0,1,3.0,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,1,0.515306,0.522293,0.622169,1
994,88.0,88.0,3,2,2,2,2,2.0,163.0,506.0,2,3.0,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1.0,1.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.494898,0.245223,0.315953,-1
999,88.0,2.0,1,1,2,2,2,2.0,152.0,504.0,2,3.0,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1.0,NaN,0.000000,0.066667,1,1,0,0,0,1,-1,-1,-1,-1,0.484694,0.210191,0.279870,-1

In [ ]:
#Preparacion atributo USENOW3

# Eliminar filas que generan ruido
df=df[df['USENOW3'] != 7.0]
df=df[df['USENOW3'] != 9.0]

#Reemplazar nulos con el valor promedio
df['USENOW3'] = df['USENOW3'].fillna((df['USENOW3'].mean()))
df['USENOW3'] = df['USENOW3'].astype(int)
#Almacenar los cambios en el nuevo atributo UsoTabacoSinHumo
df['UsoTabacoSinHumo'] = df['USENOW3'].apply(ValorNinguno)

# Crear columnas dummy (one-hot-encoding)
# Generar columnas
df = pd.concat([df, pd.get_dummies(df['UsoTabacoSinHumo'], prefix='UsTabSH')], axis=1)
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental,DiagHipertension,Hip_1,Hip_2,Hip_3,Hip_4,DiagColesterol,DiagAtaqCorazon,DiagEnfCorazon,DiagDerrCerebral,Sexo,Altura,Peso,IMC,Fumar100,UsoTabacoSinHumo,UsTabSH_1,UsTabSH_2,UsTabSH_3
0,15.0,18.0,1,1,2,2,2,2.0,280.0,510.0,1,3,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2.0,3.0,0.500000,0.600000,1,1,0,0,0,1,-1,-1,-1,-1,0.515306,0.617834,0.730997,1,3,0,0,1
1,88.0,88.0,3,2,2,2,2,2.0,165.0,508.0,1,3,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.505102,0.251592,0.318544,1,3,0,0,1
3,30.0,30.0,1,1,2,2,2,2.0,180.0,507.0,2,3,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2.0,3.0,1.000000,1.000000,1,1,0,0,0,1,-1,-1,-1,-1,0.500000,0.299363,0.375987,-1,3,0,0,1
4,20.0,88.0,3,2,2,2,2,2.0,142.0,504.0,2,3,888.0,777.0,102.0,203.0,204.0,310.0,320.0,2.0,3.0,0.666667,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.484694,0.178344,0.242725,-1,3,0,0,1
5,88.0,88.0,1,2,2,2,2,2.0,145.0,502.0,2,3,888.0,101.0,101.0,102.0,101.0,102.0,101.0,1.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.187898,0.258169,-1,3,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2.0,88.0,1,2,2,2,2,2.0,175.0,505.0,2,3,204.0,555.0,102.0,555.0,101.0,315.0,315.0,1.0,1.0,0.066667,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.489796,0.283439,0.362731,-1,3,0,0,1
992,88.0,88.0,1,2,2,2,2,2.0,140.0,502.0,2,3,230.0,330.0,202.0,330.0,203.0,202.0,330.0,2.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.171975,0.239448,-1,3,0,0,1
993,88.0,88.0,3,2,2,2,2,1.0,250.0,510.0,1,3,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,1,0.515306,0.522293,0.622169,1,3,0,0,1
994,88.0,88.0,3,2,2,2,2,2.0,163.0,506.0,2,3,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1.0,1.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.494898,0.245223,0.315953,-1,3,0,0,1
999,88.0,2.0,1,1,2,2,2,2.0,152.0,504.0,2,3,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1.0,NaN,0.000000,0.066667,1,1,0,0,0,1,-1,-1,-1,-1,0.484694,0.210191,0.279870,-1,3,0,0,1

In [ ]:
#Preparacion atributo ALCDAY5

# Eliminar filas que generan ruido
df=df[df['ALCDAY5'] != 777.0]
df=df[df['ALCDAY5'] != 999.0]
df=df[df['ALCDAY5'] != (101.0-199.0) ]

#Reemplazar nulos con el valor promedio
df['ALCDAY5'] = df['ALCDAY5'].fillna((df['ALCDAY5'].mean()))

# Reemplazar los valores predefinidos del dataset de 888(ninguna) a cero
ValorNinguno = lambda x: 0 if (x==888.0) else x

#Almacenar los cambios en el nuevo atributo CantDiaAlc30dias
df['CantDiaAlc30dias'] = df['ALCDAY5'].apply(ValorNinguno)

# Normalización: (valor-min)/(max-min)
min_veces=201
max_veces=299
NumVeces = lambda x: (x - min_veces) / (max_veces - min_veces)

#Almacenar los cambios en el nuevo atributo CantDiaAlc30dias
df['CantDiaAlc30dias'] = df['CantDiaAlc30dias'].apply(NumVeces)
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental,DiagHipertension,Hip_1,Hip_2,Hip_3,Hip_4,DiagColesterol,DiagAtaqCorazon,DiagEnfCorazon,DiagDerrCerebral,Sexo,Altura,Peso,IMC,Fumar100,UsoTabacoSinHumo,UsTabSH_1,UsTabSH_2,UsTabSH_3,CantDiaAlc30dias
0,15.0,18.0,1,1,2,2,2,2.0,280.0,510.0,1,3,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2.0,3.0,0.500000,0.600000,1,1,0,0,0,1,-1,-1,-1,-1,0.515306,0.617834,0.730997,1,3,0,0,1,-2.051020
1,88.0,88.0,3,2,2,2,2,2.0,165.0,508.0,1,3,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.505102,0.251592,0.318544,1,3,0,0,1,-2.051020
3,30.0,30.0,1,1,2,2,2,2.0,180.0,507.0,2,3,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2.0,3.0,1.000000,1.000000,1,1,0,0,0,1,-1,-1,-1,-1,0.500000,0.299363,0.375987,-1,3,0,0,1,-2.051020
4,20.0,88.0,3,2,2,2,2,2.0,142.0,504.0,2,3,888.0,777.0,102.0,203.0,204.0,310.0,320.0,2.0,3.0,0.666667,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.484694,0.178344,0.242725,-1,3,0,0,1,-2.051020
5,88.0,88.0,1,2,2,2,2,2.0,145.0,502.0,2,3,888.0,101.0,101.0,102.0,101.0,102.0,101.0,1.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.187898,0.258169,-1,3,0,0,1,-2.051020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2.0,88.0,1,2,2,2,2,2.0,175.0,505.0,2,3,204.0,555.0,102.0,555.0,101.0,315.0,315.0,1.0,1.0,0.066667,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.489796,0.283439,0.362731,-1,3,0,0,1,0.030612
992,88.0,88.0,1,2,2,2,2,2.0,140.0,502.0,2,3,230.0,330.0,202.0,330.0,203.0,202.0,330.0,2.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.171975,0.239448,-1,3,0,0,1,0.295918
993,88.0,88.0,3,2,2,2,2,1.0,250.0,510.0,1,3,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,1,0.515306,0.522293,0.622169,1,3,0,0,1,-2.051020
994,88.0,88.0,3,2,2,2,2,2.0,163.0,506.0,2,3,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1.0,1.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.494898,0.245223,0.315953,-1,3,0,0,1,-2.051020
999,88.0,2.0,1,1,2,2,2,2.0,152.0,504.0,2,3,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1.0,NaN,0.000000,0.066667,1,1,0,0,0,1,-1,-1,-1,-1,0.484694,0.210191,0.279870,-1,3,0,0,1,-2.051020

In [ ]:
#Preparacion atributo FRUITJU1

# Eliminar filas que generan ruido
df=df[df['FRUITJU1'] != 777.0]
df=df[df['FRUITJU1'] != 999.0]
df=df[df['FRUITJU1'] != (101.0-299.0) ]

#Reemplazar nulos con el valor promedio
df['FRUITJU1'] = df['FRUITJU1'].fillna((df['FRUITJU1'].mean()))

# Reemplazar los valores predefinidos del dataset de 555(ninguna) a cero
ValorNinguno = lambda x: 0 if (x==555.0) else x

#Almacenar los cambios en el nuevo atributo JugFru30dias
df['JugFru30dias'] = df['FRUITJU1'].apply(ValorNinguno)

# Normalización: (valor-min)/(max-min)
min_veces=300
max_veces=399
NumVeces = lambda x: (x - min_veces) / (max_veces - min_veces)

#Almacenar los cambios en el nuevo atributo JugFru30dias
df['JugFru30dias'] = df['JugFru30dias'].apply(NumVeces)
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental,DiagHipertension,Hip_1,Hip_2,Hip_3,Hip_4,DiagColesterol,DiagAtaqCorazon,DiagEnfCorazon,DiagDerrCerebral,Sexo,Altura,Peso,IMC,Fumar100,UsoTabacoSinHumo,UsTabSH_1,UsTabSH_2,UsTabSH_3,CantDiaAlc30dias,JugFru30dias
0,15.0,18.0,1,1,2,2,2,2.0,280.0,510.0,1,3,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2.0,3.0,0.500000,0.600000,1,1,0,0,0,1,-1,-1,-1,-1,0.515306,0.617834,0.730997,1,3,0,0,1,-2.051020,0.050505
1,88.0,88.0,3,2,2,2,2,2.0,165.0,508.0,1,3,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.505102,0.251592,0.318544,1,3,0,0,1,-2.051020,0.020202
3,30.0,30.0,1,1,2,2,2,2.0,180.0,507.0,2,3,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2.0,3.0,1.000000,1.000000,1,1,0,0,0,1,-1,-1,-1,-1,0.500000,0.299363,0.375987,-1,3,0,0,1,-2.051020,-3.030303
5,88.0,88.0,1,2,2,2,2,2.0,145.0,502.0,2,3,888.0,101.0,101.0,102.0,101.0,102.0,101.0,1.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.187898,0.258169,-1,3,0,0,1,-2.051020,-2.010101
6,88.0,3.0,1,1,2,2,2,2.0,148.0,506.0,2,3,203.0,330.0,202.0,302.0,202.0,302.0,205.0,1.0,3.0,0.000000,0.100000,1,1,0,0,0,1,-1,-1,-1,-1,0.494898,0.197452,0.260675,-1,3,0,0,1,0.020408,0.303030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2.0,88.0,1,2,2,2,2,2.0,175.0,505.0,2,3,204.0,555.0,102.0,555.0,101.0,315.0,315.0,1.0,1.0,0.066667,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.489796,0.283439,0.362731,-1,3,0,0,1,0.030612,-3.030303
992,88.0,88.0,1,2,2,2,2,2.0,140.0,502.0,2,3,230.0,330.0,202.0,330.0,203.0,202.0,330.0,2.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.171975,0.239448,-1,3,0,0,1,0.295918,0.303030
993,88.0,88.0,3,2,2,2,2,1.0,250.0,510.0,1,3,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,1,0.515306,0.522293,0.622169,1,3,0,0,1,-2.051020,-0.989899
994,88.0,88.0,3,2,2,2,2,2.0,163.0,506.0,2,3,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1.0,1.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.494898,0.245223,0.315953,-1,3,0,0,1,-2.051020,-3.030303
999,88.0,2.0,1,1,2,2,2,2.0,152.0,504.0,2,3,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1.0,NaN,0.000000,0.066667,1,1,0,0,0,1,-1,-1,-1,-1,0.484694,0.210191,0.279870,-1,3,0,0,1,-2.051020,-0.979798

In [ ]:
#Preparacion atributo FRUIT1

# Eliminar filas que generan ruido
df=df[df['FRUIT1'] != 777.0]
df=df[df['FRUIT1'] != 999.0]
df=df[df['FRUIT1'] != (101.0-299.0) ]

#Reemplazar nulos con el valor promedio
df['FRUIT1'] = df['FRUIT1'].fillna((df['FRUIT1'].mean()))

# Reemplazar los valores predefinidos del dataset de 555(ninguna) a cero
ValorNinguno = lambda x: 0 if (x==555.0) else x

#Almacenar los cambios en el nuevo atributo Fruta30dias
df['Fruta30dias'] = df['FRUIT1'].apply(ValorNinguno)

# Normalización: (valor-min)/(max-min)
min_veces=300
max_veces=399
NumVeces = lambda x: (x - min_veces) / (max_veces - min_veces)

#Almacenar los cambios en el nuevo atributo Fruta30dias
df['Fruta30dias'] = df['Fruta30dias'].apply(NumVeces)
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental,DiagHipertension,Hip_1,Hip_2,Hip_3,Hip_4,DiagColesterol,DiagAtaqCorazon,DiagEnfCorazon,DiagDerrCerebral,Sexo,Altura,Peso,IMC,Fumar100,UsoTabacoSinHumo,UsTabSH_1,UsTabSH_2,UsTabSH_3,CantDiaAlc30dias,JugFru30dias,Fruta30dias
0,15.0,18.0,1,1,2,2,2,2.0,280.0,510.0,1,3,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2.0,3.0,0.500000,0.600000,1,1,0,0,0,1,-1,-1,-1,-1,0.515306,0.617834,0.730997,1,3,0,0,1,-2.051020,0.050505,0.101010
1,88.0,88.0,3,2,2,2,2,2.0,165.0,508.0,1,3,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.505102,0.251592,0.318544,1,3,0,0,1,-2.051020,0.020202,0.050505
3,30.0,30.0,1,1,2,2,2,2.0,180.0,507.0,2,3,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2.0,3.0,1.000000,1.000000,1,1,0,0,0,1,-1,-1,-1,-1,0.500000,0.299363,0.375987,-1,3,0,0,1,-2.051020,-3.030303,-2.010101
5,88.0,88.0,1,2,2,2,2,2.0,145.0,502.0,2,3,888.0,101.0,101.0,102.0,101.0,102.0,101.0,1.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.187898,0.258169,-1,3,0,0,1,-2.051020,-2.010101,-2.010101
6,88.0,3.0,1,1,2,2,2,2.0,148.0,506.0,2,3,203.0,330.0,202.0,302.0,202.0,302.0,205.0,1.0,3.0,0.000000,0.100000,1,1,0,0,0,1,-1,-1,-1,-1,0.494898,0.197452,0.260675,-1,3,0,0,1,0.020408,0.303030,-0.989899
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2.0,88.0,1,2,2,2,2,2.0,175.0,505.0,2,3,204.0,555.0,102.0,555.0,101.0,315.0,315.0,1.0,1.0,0.066667,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.489796,0.283439,0.362731,-1,3,0,0,1,0.030612,-3.030303,-2.000000
992,88.0,88.0,1,2,2,2,2,2.0,140.0,502.0,2,3,230.0,330.0,202.0,330.0,203.0,202.0,330.0,2.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.171975,0.239448,-1,3,0,0,1,0.295918,0.303030,-0.989899
993,88.0,88.0,3,2,2,2,2,1.0,250.0,510.0,1,3,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,1,0.515306,0.522293,0.622169,1,3,0,0,1,-2.051020,-0.989899,-0.979798
994,88.0,88.0,3,2,2,2,2,2.0,163.0,506.0,2,3,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1.0,1.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.494898,0.245223,0.315953,-1,3,0,0,1,-2.051020,-3.030303,-2.000000
999,88.0,2.0,1,1,2,2,2,2.0,152.0,504.0,2,3,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1.0,NaN,0.000000,0.066667,1,1,0,0,0,1,-1,-1,-1,-1,0.484694,0.210191,0.279870,-1,3,0,0,1,-2.051020,-0.979798,-2.000000

In [ ]:
#Preparacion atributo FVBEANS

# Eliminar filas que generan ruido
df=df[df['FVBEANS'] != 777.0]
df=df[df['FVBEANS'] != 999.0]
df=df[df['FVBEANS'] != (101.0-299.0) ]

#Reemplazar nulos con el valor promedio
df['FVBEANS'] = df['FVBEANS'].fillna((df['FVBEANS'].mean()))

# Reemplazar los valores predefinidos del dataset de 555(ninguna) a cero
ValorNinguno = lambda x: 0 if (x==555.0) else x

#Almacenar los cambios en el nuevo atributo Leg30dias
df['Leg30dias'] = df['FVBEANS'].apply(ValorNinguno)

# Normalización: (valor-min)/(max-min)
min_veces=300
max_veces=399
NumVeces = lambda x: (x - min_veces) / (max_veces - min_veces)

#Almacenar los cambios en el nuevo atributo Leg30dias
df['Leg30dias'] = df['Leg30dias'].apply(NumVeces)
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental,DiagHipertension,Hip_1,Hip_2,Hip_3,Hip_4,DiagColesterol,DiagAtaqCorazon,DiagEnfCorazon,DiagDerrCerebral,Sexo,Altura,Peso,IMC,Fumar100,UsoTabacoSinHumo,UsTabSH_1,UsTabSH_2,UsTabSH_3,CantDiaAlc30dias,JugFru30dias,Fruta30dias,Leg30dias
0,15.0,18.0,1,1,2,2,2,2.0,280.0,510.0,1,3,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2.0,3.0,0.500000,0.600000,1,1,0,0,0,1,-1,-1,-1,-1,0.515306,0.617834,0.730997,1,3,0,0,1,-2.051020,0.050505,0.101010,0.202020
1,88.0,88.0,3,2,2,2,2,2.0,165.0,508.0,1,3,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.505102,0.251592,0.318544,1,3,0,0,1,-2.051020,0.020202,0.050505,0.020202
3,30.0,30.0,1,1,2,2,2,2.0,180.0,507.0,2,3,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2.0,3.0,1.000000,1.000000,1,1,0,0,0,1,-1,-1,-1,-1,0.500000,0.299363,0.375987,-1,3,0,0,1,-2.051020,-3.030303,-2.010101,-3.030303
5,88.0,88.0,1,2,2,2,2,2.0,145.0,502.0,2,3,888.0,101.0,101.0,102.0,101.0,102.0,101.0,1.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.187898,0.258169,-1,3,0,0,1,-2.051020,-2.010101,-2.010101,-2.000000
6,88.0,3.0,1,1,2,2,2,2.0,148.0,506.0,2,3,203.0,330.0,202.0,302.0,202.0,302.0,205.0,1.0,3.0,0.000000,0.100000,1,1,0,0,0,1,-1,-1,-1,-1,0.494898,0.197452,0.260675,-1,3,0,0,1,0.020408,0.303030,-0.989899,0.020202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2.0,88.0,1,2,2,2,2,2.0,175.0,505.0,2,3,204.0,555.0,102.0,555.0,101.0,315.0,315.0,1.0,1.0,0.066667,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.489796,0.283439,0.362731,-1,3,0,0,1,0.030612,-3.030303,-2.000000,-3.030303
992,88.0,88.0,1,2,2,2,2,2.0,140.0,502.0,2,3,230.0,330.0,202.0,330.0,203.0,202.0,330.0,2.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.171975,0.239448,-1,3,0,0,1,0.295918,0.303030,-0.989899,0.303030
993,88.0,88.0,3,2,2,2,2,1.0,250.0,510.0,1,3,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,1,0.515306,0.522293,0.622169,1,3,0,0,1,-2.051020,-0.989899,-0.979798,-3.030303
994,88.0,88.0,3,2,2,2,2,2.0,163.0,506.0,2,3,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1.0,1.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.494898,0.245223,0.315953,-1,3,0,0,1,-2.051020,-3.030303,-2.000000,0.020202
999,88.0,2.0,1,1,2,2,2,2.0,152.0,504.0,2,3,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1.0,NaN,0.000000,0.066667,1,1,0,0,0,1,-1,-1,-1,-1,0.484694,0.210191,0.279870,-1,3,0,0,1,-2.051020,-0.979798,-2.000000,-1.000000

In [ ]:
#Preparacion atributo FVGREEN

# Eliminar filas que generan ruido
df=df[df['FVGREEN'] != 777.0]
df=df[df['FVGREEN'] != 999.0]
df=df[df['FVGREEN'] != (101.0-299.0) ]

#Reemplazar nulos con el valor promedio
df['FVGREEN'] = df['FVGREEN'].fillna((df['FVGREEN'].mean()))

# Reemplazar los valores predefinidos del dataset de 555(ninguna) a cero
ValorNinguno = lambda x: 0 if (x==555.0) else x

#Almacenar los cambios en el nuevo atributo VerVerde30dias
df['VerVerde30dias'] = df['FVGREEN'].apply(ValorNinguno)

# Normalización: (valor-min)/(max-min)
min_veces=300
max_veces=309
NumVeces = lambda x: (x - min_veces) / (max_veces - min_veces)

#Almacenar los cambios en el nuevo atributo VerVerde30dias
df['VerVerde30dias'] = df['VerVerde30dias'].apply(NumVeces)
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental,DiagHipertension,Hip_1,Hip_2,Hip_3,Hip_4,DiagColesterol,DiagAtaqCorazon,DiagEnfCorazon,DiagDerrCerebral,Sexo,Altura,Peso,IMC,Fumar100,UsoTabacoSinHumo,UsTabSH_1,UsTabSH_2,UsTabSH_3,CantDiaAlc30dias,JugFru30dias,Fruta30dias,Leg30dias,VerVerde30dias
0,15.0,18.0,1,1,2,2,2,2.0,280.0,510.0,1,3,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2.0,3.0,0.500000,0.600000,1,1,0,0,0,1,-1,-1,-1,-1,0.515306,0.617834,0.730997,1,3,0,0,1,-2.051020,0.050505,0.101010,0.202020,1.111111
1,88.0,88.0,3,2,2,2,2,2.0,165.0,508.0,1,3,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.505102,0.251592,0.318544,1,3,0,0,1,-2.051020,0.020202,0.050505,0.020202,-10.888889
3,30.0,30.0,1,1,2,2,2,2.0,180.0,507.0,2,3,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2.0,3.0,1.000000,1.000000,1,1,0,0,0,1,-1,-1,-1,-1,0.500000,0.299363,0.375987,-1,3,0,0,1,-2.051020,-3.030303,-2.010101,-3.030303,0.111111
5,88.0,88.0,1,2,2,2,2,2.0,145.0,502.0,2,3,888.0,101.0,101.0,102.0,101.0,102.0,101.0,1.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.187898,0.258169,-1,3,0,0,1,-2.051020,-2.010101,-2.010101,-2.000000,-22.111111
6,88.0,3.0,1,1,2,2,2,2.0,148.0,506.0,2,3,203.0,330.0,202.0,302.0,202.0,302.0,205.0,1.0,3.0,0.000000,0.100000,1,1,0,0,0,1,-1,-1,-1,-1,0.494898,0.197452,0.260675,-1,3,0,0,1,0.020408,0.303030,-0.989899,0.020202,-10.888889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2.0,88.0,1,2,2,2,2,2.0,175.0,505.0,2,3,204.0,555.0,102.0,555.0,101.0,315.0,315.0,1.0,1.0,0.066667,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.489796,0.283439,0.362731,-1,3,0,0,1,0.030612,-3.030303,-2.000000,-3.030303,-22.111111
992,88.0,88.0,1,2,2,2,2,2.0,140.0,502.0,2,3,230.0,330.0,202.0,330.0,203.0,202.0,330.0,2.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.171975,0.239448,-1,3,0,0,1,0.295918,0.303030,-0.989899,0.303030,-10.777778
993,88.0,88.0,3,2,2,2,2,1.0,250.0,510.0,1,3,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,1,0.515306,0.522293,0.622169,1,3,0,0,1,-2.051020,-0.989899,-0.979798,-3.030303,-10.888889
994,88.0,88.0,3,2,2,2,2,2.0,163.0,506.0,2,3,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1.0,1.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.494898,0.245223,0.315953,-1,3,0,0,1,-2.051020,-3.030303,-2.000000,0.020202,-10.777778
999,88.0,2.0,1,1,2,2,2,2.0,152.0,504.0,2,3,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1.0,NaN,0.000000,0.066667,1,1,0,0,0,1,-1,-1,-1,-1,0.484694,0.210191,0.279870,-1,3,0,0,1,-2.051020,-0.979798,-2.000000,-1.000000,-22.111111

In [ ]:
#Preparacion atributo FVORANG

# Eliminar filas que generan ruido
df=df[df['FVORANG'] != 777.0]
df=df[df['FVORANG'] != 999.0]
df=df[df['FVORANG'] != (101.0-299.0) ]

#Reemplazar nulos con el valor promedio
df['FVORANG'] = df['FVORANG'].fillna((df['FVORANG'].mean()))

# Reemplazar los valores predefinidos del dataset de 555(ninguna) a cero
ValorNinguno = lambda x: 0 if (x==555.0) else x

#Almacenar los cambios en el nuevo atributo VerNar30dias
df['VerNar30dias'] = df['FVORANG'].apply(ValorNinguno)

# Normalización: (valor-min)/(max-min)
min_veces=300
max_veces=399
NumVeces = lambda x: (x - min_veces) / (max_veces - min_veces)

#Almacenar los cambios en el nuevo atributo VerNar30dias
df['VerNar30dias'] = df['VerNar30dias'].apply(NumVeces)
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental,DiagHipertension,Hip_1,Hip_2,Hip_3,Hip_4,DiagColesterol,DiagAtaqCorazon,DiagEnfCorazon,DiagDerrCerebral,Sexo,Altura,Peso,IMC,Fumar100,UsoTabacoSinHumo,UsTabSH_1,UsTabSH_2,UsTabSH_3,CantDiaAlc30dias,JugFru30dias,Fruta30dias,Leg30dias,VerVerde30dias,VerNar30dias
0,15.0,18.0,1,1,2,2,2,2.0,280.0,510.0,1,3,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2.0,3.0,0.500000,0.600000,1,1,0,0,0,1,-1,-1,-1,-1,0.515306,0.617834,0.730997,1,3,0,0,1,-2.051020,0.050505,0.101010,0.202020,1.111111,0.050505
1,88.0,88.0,3,2,2,2,2,2.0,165.0,508.0,1,3,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.505102,0.251592,0.318544,1,3,0,0,1,-2.051020,0.020202,0.050505,0.020202,-10.888889,-0.989899
3,30.0,30.0,1,1,2,2,2,2.0,180.0,507.0,2,3,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2.0,3.0,1.000000,1.000000,1,1,0,0,0,1,-1,-1,-1,-1,0.500000,0.299363,0.375987,-1,3,0,0,1,-2.051020,-3.030303,-2.010101,-3.030303,0.111111,0.010101
5,88.0,88.0,1,2,2,2,2,2.0,145.0,502.0,2,3,888.0,101.0,101.0,102.0,101.0,102.0,101.0,1.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.187898,0.258169,-1,3,0,0,1,-2.051020,-2.010101,-2.010101,-2.000000,-22.111111,-2.000000
6,88.0,3.0,1,1,2,2,2,2.0,148.0,506.0,2,3,203.0,330.0,202.0,302.0,202.0,302.0,205.0,1.0,3.0,0.000000,0.100000,1,1,0,0,0,1,-1,-1,-1,-1,0.494898,0.197452,0.260675,-1,3,0,0,1,0.020408,0.303030,-0.989899,0.020202,-10.888889,0.020202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2.0,88.0,1,2,2,2,2,2.0,175.0,505.0,2,3,204.0,555.0,102.0,555.0,101.0,315.0,315.0,1.0,1.0,0.066667,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.489796,0.283439,0.362731,-1,3,0,0,1,0.030612,-3.030303,-2.000000,-3.030303,-22.111111,0.151515
992,88.0,88.0,1,2,2,2,2,2.0,140.0,502.0,2,3,230.0,330.0,202.0,330.0,203.0,202.0,330.0,2.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.171975,0.239448,-1,3,0,0,1,0.295918,0.303030,-0.989899,0.303030,-10.777778,-0.989899
993,88.0,88.0,3,2,2,2,2,1.0,250.0,510.0,1,3,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,1,0.515306,0.522293,0.622169,1,3,0,0,1,-2.051020,-0.989899,-0.979798,-3.030303,-10.888889,-0.989899
994,88.0,88.0,3,2,2,2,2,2.0,163.0,506.0,2,3,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1.0,1.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.494898,0.245223,0.315953,-1,3,0,0,1,-2.051020,-3.030303,-2.000000,0.020202,-10.777778,0.050505
999,88.0,2.0,1,1,2,2,2,2.0,152.0,504.0,2,3,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1.0,NaN,0.000000,0.066667,1,1,0,0,0,1,-1,-1,-1,-1,0.484694,0.210191,0.279870,-1,3,0,0,1,-2.051020,-0.979798,-2.000000,-1.000000,-22.111111,-0.979798

In [ ]:
#Preparacion atributo VEGETAB1

# Eliminar filas que generan ruido
df=df[df['VEGETAB1'] != 777.0]
df=df[df['VEGETAB1'] != 999.0]

#Reemplazar nulos con el valor promedio
df['VEGETAB1'] = df['VEGETAB1'].fillna((df['VEGETAB1'].mean()))

# Reemplazar los valores predefinidos del dataset de 555(ninguna) a cero
ValorNinguno = lambda x: 0 if (x==555.0) else x

#Almacenar los cambios en el nuevo atributo OtrVer30dias
df['OtrVer30dias'] = df['VEGETAB1'].apply(ValorNinguno)

# Normalización: (valor-min)/(max-min)
min_veces=300
max_veces=399
NumVeces = lambda x: (x - min_veces) / (max_veces - min_veces)

#Almacenar los cambios en el nuevo atributo OtrVer30dias
df['OtrVer30dias'] = df['OtrVer30dias'].apply(NumVeces)
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental,DiagHipertension,Hip_1,Hip_2,Hip_3,Hip_4,DiagColesterol,DiagAtaqCorazon,DiagEnfCorazon,DiagDerrCerebral,Sexo,Altura,Peso,IMC,Fumar100,UsoTabacoSinHumo,UsTabSH_1,UsTabSH_2,UsTabSH_3,CantDiaAlc30dias,JugFru30dias,Fruta30dias,Leg30dias,VerVerde30dias,VerNar30dias,OtrVer30dias
0,15.0,18.0,1,1,2,2,2,2.0,280.0,510.0,1,3,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2.0,3.0,0.500000,0.600000,1,1,0,0,0,1,-1,-1,-1,-1,0.515306,0.617834,0.730997,1,3,0,0,1,-2.051020,0.050505,0.101010,0.202020,1.111111,0.050505,-2.010101
1,88.0,88.0,3,2,2,2,2,2.0,165.0,508.0,1,3,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.505102,0.251592,0.318544,1,3,0,0,1,-2.051020,0.020202,0.050505,0.020202,-10.888889,-0.989899,0.040404
3,30.0,30.0,1,1,2,2,2,2.0,180.0,507.0,2,3,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2.0,3.0,1.000000,1.000000,1,1,0,0,0,1,-1,-1,-1,-1,0.500000,0.299363,0.375987,-1,3,0,0,1,-2.051020,-3.030303,-2.010101,-3.030303,0.111111,0.010101,-1.000000
5,88.0,88.0,1,2,2,2,2,2.0,145.0,502.0,2,3,888.0,101.0,101.0,102.0,101.0,102.0,101.0,1.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.187898,0.258169,-1,3,0,0,1,-2.051020,-2.010101,-2.010101,-2.000000,-22.111111,-2.000000,-2.010101
6,88.0,3.0,1,1,2,2,2,2.0,148.0,506.0,2,3,203.0,330.0,202.0,302.0,202.0,302.0,205.0,1.0,3.0,0.000000,0.100000,1,1,0,0,0,1,-1,-1,-1,-1,0.494898,0.197452,0.260675,-1,3,0,0,1,0.020408,0.303030,-0.989899,0.020202,-10.888889,0.020202,-0.959596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2.0,88.0,1,2,2,2,2,2.0,175.0,505.0,2,3,204.0,555.0,102.0,555.0,101.0,315.0,315.0,1.0,1.0,0.066667,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.489796,0.283439,0.362731,-1,3,0,0,1,0.030612,-3.030303,-2.000000,-3.030303,-22.111111,0.151515,0.151515
992,88.0,88.0,1,2,2,2,2,2.0,140.0,502.0,2,3,230.0,330.0,202.0,330.0,203.0,202.0,330.0,2.0,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.171975,0.239448,-1,3,0,0,1,0.295918,0.303030,-0.989899,0.303030,-10.777778,-0.989899,0.303030
993,88.0,88.0,3,2,2,2,2,1.0,250.0,510.0,1,3,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1.0,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,1,0.515306,0.522293,0.622169,1,3,0,0,1,-2.051020,-0.989899,-0.979798,-3.030303,-10.888889,-0.989899,-0.989899
994,88.0,88.0,3,2,2,2,2,2.0,163.0,506.0,2,3,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1.0,1.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.494898,0.245223,0.315953,-1,3,0,0,1,-2.051020,-3.030303,-2.000000,0.020202,-10.777778,0.050505,-2.000000
999,88.0,2.0,1,1,2,2,2,2.0,152.0,504.0,2,3,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1.0,NaN,0.000000,0.066667,1,1,0,0,0,1,-1,-1,-1,-1,0.484694,0.210191,0.279870,-1,3,0,0,1,-2.051020,-0.979798,-2.000000,-1.000000,-22.111111,-0.979798,-2.000000

In [ ]:
#Preparacion atributo EXERANY2

# Eliminar filas que generan ruido
df=df[df['EXERANY2'] != 7.0]
df=df[df['EXERANY2'] != 9.0]

#Reemplazar nulos con el valor promedio
df['EXERANY2'] = df['EXERANY2'].fillna((df['EXERANY2'].mean()))
df['EXERANY2'] = df['EXERANY2'].astype(int)

# Reemplazar los valores predefinidos del dataset de 88(ninguna) a cero
ValorNinguno = lambda x: 0 if (x==88.0) else x

#Almacenar los cambios en el nuevo atributo Ejerc30dias
df['Ejerc30dias'] = df['EXERANY2'].apply(ValorNinguno)

# Normalización: 1 y -1
convertir_ejercicio30 = lambda x: 1 if (x==1) else -1
df['Ejerc30dias'] = df['Ejerc30dias'].apply(convertir_ejercicio30)
df

#Almacenar los cambios en el nuevo atributo Ejerc30dias
df['Ejerc30dias'] = df['Ejerc30dias'].apply(convertir_ejercicio30)
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental,DiagHipertension,Hip_1,Hip_2,Hip_3,Hip_4,DiagColesterol,DiagAtaqCorazon,DiagEnfCorazon,DiagDerrCerebral,Sexo,Altura,Peso,IMC,Fumar100,UsoTabacoSinHumo,UsTabSH_1,UsTabSH_2,UsTabSH_3,CantDiaAlc30dias,JugFru30dias,Fruta30dias,Leg30dias,VerVerde30dias,VerNar30dias,OtrVer30dias,Ejerc30dias
0,15.0,18.0,1,1,2,2,2,2.0,280.0,510.0,1,3,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2,3.0,0.500000,0.600000,1,1,0,0,0,1,-1,-1,-1,-1,0.515306,0.617834,0.730997,1,3,0,0,1,-2.051020,0.050505,0.101010,0.202020,1.111111,0.050505,-2.010101,-1
1,88.0,88.0,3,2,2,2,2,2.0,165.0,508.0,1,3,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.505102,0.251592,0.318544,1,3,0,0,1,-2.051020,0.020202,0.050505,0.020202,-10.888889,-0.989899,0.040404,1
3,30.0,30.0,1,1,2,2,2,2.0,180.0,507.0,2,3,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2,3.0,1.000000,1.000000,1,1,0,0,0,1,-1,-1,-1,-1,0.500000,0.299363,0.375987,-1,3,0,0,1,-2.051020,-3.030303,-2.010101,-3.030303,0.111111,0.010101,-1.000000,-1
5,88.0,88.0,1,2,2,2,2,2.0,145.0,502.0,2,3,888.0,101.0,101.0,102.0,101.0,102.0,101.0,1,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.187898,0.258169,-1,3,0,0,1,-2.051020,-2.010101,-2.010101,-2.000000,-22.111111,-2.000000,-2.010101,1
6,88.0,3.0,1,1,2,2,2,2.0,148.0,506.0,2,3,203.0,330.0,202.0,302.0,202.0,302.0,205.0,1,3.0,0.000000,0.100000,1,1,0,0,0,1,-1,-1,-1,-1,0.494898,0.197452,0.260675,-1,3,0,0,1,0.020408,0.303030,-0.989899,0.020202,-10.888889,0.020202,-0.959596,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2.0,88.0,1,2,2,2,2,2.0,175.0,505.0,2,3,204.0,555.0,102.0,555.0,101.0,315.0,315.0,1,1.0,0.066667,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.489796,0.283439,0.362731,-1,3,0,0,1,0.030612,-3.030303,-2.000000,-3.030303,-22.111111,0.151515,0.151515,1
992,88.0,88.0,1,2,2,2,2,2.0,140.0,502.0,2,3,230.0,330.0,202.0,330.0,203.0,202.0,330.0,2,3.0,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.171975,0.239448,-1,3,0,0,1,0.295918,0.303030,-0.989899,0.303030,-10.777778,-0.989899,0.303030,-1
993,88.0,88.0,3,2,2,2,2,1.0,250.0,510.0,1,3,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1,3.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,1,0.515306,0.522293,0.622169,1,3,0,0,1,-2.051020,-0.989899,-0.979798,-3.030303,-10.888889,-0.989899,-0.989899,1
994,88.0,88.0,3,2,2,2,2,2.0,163.0,506.0,2,3,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1,1.0,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.494898,0.245223,0.315953,-1,3,0,0,1,-2.051020,-3.030303,-2.000000,0.020202,-10.777778,0.050505,-2.000000,1
999,88.0,2.0,1,1,2,2,2,2.0,152.0,504.0,2,3,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1,NaN,0.000000,0.066667,1,1,0,0,0,1,-1,-1,-1,-1,0.484694,0.210191,0.279870,-1,3,0,0,1,-2.051020,-0.979798,-2.000000,-1.000000,-22.111111,-0.979798,-2.000000,1

In [ ]:
#Preparacion atributo PREDIAB1

# Eliminar filas que generan ruido
df=df[df['PREDIAB1'] != 7.0]
df=df[df['PREDIAB1'] != 9.0]

#Reemplazar nulos con el valor promedio
df['PREDIAB1'] = df['PREDIAB1'].fillna((df['PREDIAB1'].mean()))
df['PREDIAB1'] = df['PREDIAB1'].astype(int)
#Almacenar los cambios en el nuevo atributo DiagDiabetes
df['DiagDiabetes'] = df['PREDIAB1'].apply(ValorNinguno)

# Crear columnas dummy (one-hot-encoding)
# Generar columnas
df = pd.concat([df, pd.get_dummies(df['DiagDiabetes'], prefix='Diab')], axis=1)
df

,PHYSHLTH,MENTHLTH,BPHIGH4,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,WEIGHT2,HEIGHT3,SMOKE100,USENOW3,ALCDAY5,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,PREDIAB1,SaludFisica,SaludMental,DiagHipertension,Hip_1,Hip_2,Hip_3,Hip_4,DiagColesterol,DiagAtaqCorazon,DiagEnfCorazon,DiagDerrCerebral,Sexo,Altura,Peso,IMC,Fumar100,UsoTabacoSinHumo,UsTabSH_1,UsTabSH_2,UsTabSH_3,CantDiaAlc30dias,JugFru30dias,Fruta30dias,Leg30dias,VerVerde30dias,VerNar30dias,OtrVer30dias,Ejerc30dias,DiagDiabetes,Diab_1,Diab_2,Diab_3
0,15.0,18.0,1,1,2,2,2,2.0,280.0,510.0,1,3,888.0,305.0,310.0,320.0,310.0,305.0,101.0,2,3,0.500000,0.600000,1,1,0,0,0,1,-1,-1,-1,-1,0.515306,0.617834,0.730997,1,3,0,0,1,-2.051020,0.050505,0.101010,0.202020,1.111111,0.050505,-2.010101,-1,3,0,0,1
1,88.0,88.0,3,2,2,2,2,2.0,165.0,508.0,1,3,888.0,302.0,305.0,302.0,202.0,202.0,304.0,1,3,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.505102,0.251592,0.318544,1,3,0,0,1,-2.051020,0.020202,0.050505,0.020202,-10.888889,-0.989899,0.040404,1,3,0,0,1
3,30.0,30.0,1,1,2,2,2,2.0,180.0,507.0,2,3,888.0,555.0,101.0,555.0,301.0,301.0,201.0,2,3,1.000000,1.000000,1,1,0,0,0,1,-1,-1,-1,-1,0.500000,0.299363,0.375987,-1,3,0,0,1,-2.051020,-3.030303,-2.010101,-3.030303,0.111111,0.010101,-1.000000,-1,3,0,0,1
5,88.0,88.0,1,2,2,2,2,2.0,145.0,502.0,2,3,888.0,101.0,101.0,102.0,101.0,102.0,101.0,1,3,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.187898,0.258169,-1,3,0,0,1,-2.051020,-2.010101,-2.010101,-2.000000,-22.111111,-2.000000,-2.010101,1,3,0,0,1
6,88.0,3.0,1,1,2,2,2,2.0,148.0,506.0,2,3,203.0,330.0,202.0,302.0,202.0,302.0,205.0,1,3,0.000000,0.100000,1,1,0,0,0,1,-1,-1,-1,-1,0.494898,0.197452,0.260675,-1,3,0,0,1,0.020408,0.303030,-0.989899,0.020202,-10.888889,0.020202,-0.959596,1,3,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2.0,88.0,1,2,2,2,2,2.0,175.0,505.0,2,3,204.0,555.0,102.0,555.0,101.0,315.0,315.0,1,1,0.066667,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.489796,0.283439,0.362731,-1,3,0,0,1,0.030612,-3.030303,-2.000000,-3.030303,-22.111111,0.151515,0.151515,1,1,1,0,0
992,88.0,88.0,1,2,2,2,2,2.0,140.0,502.0,2,3,230.0,330.0,202.0,330.0,203.0,202.0,330.0,2,3,0.000000,0.000000,1,1,0,0,0,-1,-1,-1,-1,-1,0.474490,0.171975,0.239448,-1,3,0,0,1,0.295918,0.303030,-0.989899,0.303030,-10.777778,-0.989899,0.303030,-1,3,0,0,1
993,88.0,88.0,3,2,2,2,2,1.0,250.0,510.0,1,3,888.0,202.0,203.0,555.0,202.0,202.0,202.0,1,3,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,1,0.515306,0.522293,0.622169,1,3,0,0,1,-2.051020,-0.989899,-0.979798,-3.030303,-10.888889,-0.989899,-0.989899,1,3,0,0,1
994,88.0,88.0,3,2,2,2,2,2.0,163.0,506.0,2,3,888.0,555.0,102.0,302.0,203.0,305.0,102.0,1,1,0.000000,0.000000,3,0,0,1,0,-1,-1,-1,-1,-1,0.494898,0.245223,0.315953,-1,3,0,0,1,-2.051020,-3.030303,-2.000000,0.020202,-10.777778,0.050505,-2.000000,1,1,1,0,0
999,88.0,2.0,1,1,2,2,2,2.0,152.0,504.0,2,3,888.0,203.0,102.0,201.0,101.0,203.0,102.0,1,2,0.000000,0.066667,1,1,0,0,0,1,-1,-1,-1,-1,0.484694,0.210191,0.279870,-1,3,0,0,1,-2.051020,-0.979798,-2.000000,-1.000000,-22.111111,-0.979798,-2.000000,1,2,0,1,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 786 entries, 0 to 999
Data columns (total 53 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PHYSHLTH          786 non-null    float64
 1   MENTHLTH          786 non-null    float64
 2   BPHIGH4           786 non-null    int64
 3   TOLDHI2           786 non-null    int64
 4   CVDINFR4          786 non-null    int64
 5   CVDCRHD4          786 non-null    int64
 6   CVDSTRK3          786 non-null    int64
 7   SEX               786 non-null    float64
 8   WEIGHT2           786 non-null    float64
 9   HEIGHT3           786 non-null    float64
 10  SMOKE100          786 non-null    int64
 11  USENOW3           786 non-null    int64
 12  ALCDAY5           786 non-null    float64
 13  FRUITJU1          786 non-null    float64
 14  FRUIT1            786 non-null    float64
 15  FVBEANS           786 non-null    float64
 16  FVGREEN           786 non-null    float64
 17  FVORANG           786 non-null    float64
 18  VEGETAB1          786 non-null    float64
 19  EXERANY2          786 non-null    int64
 20  PREDIAB1          786 non-null    int64
 21  SaludFisica       786 non-null    float64
 22  SaludMental       786 non-null    float64
 23  DiagHipertension  786 non-null    int64
 24  Hip_1             786 non-null    uint8
 25  Hip_2             786 non-null    uint8
 26  Hip_3             786 non-null    uint8
 27  Hip_4             786 non-null    uint8
 28  DiagColesterol    786 non-null    int64
 29  DiagAtaqCorazon   786 non-null    int64
 30  DiagEnfCorazon    786 non-null    int64
 31  DiagDerrCerebral  786 non-null    int64
 32  Sexo              786 non-null    int64
 33  Altura            786 non-null    float64
 34  Peso              786 non-null    float64
 35  IMC               786 non-null    float64
 36  Fumar100          786 non-null    int64
 37  UsoTabacoSinHumo  786 non-null    int64
 38  UsTabSH_1         786 non-null    uint8
 39  UsTabSH_2         786 non-null    uint8
 40  UsTabSH_3         786 non-null    uint8
 41  CantDiaAlc30dias  786 non-null    float64
 42  JugFru30dias      786 non-null    float64
 43  Fruta30dias       786 non-null    float64
 44  Leg30dias         786 non-null    float64
 45  VerVerde30dias    786 non-null    float64
 46  VerNar30dias      786 non-null    float64
 47  OtrVer30dias      786 non-null    float64
 48  Ejerc30dias       786 non-null    int64
 49  DiagDiabetes      786 non-null    int64
 50  Diab_1            786 non-null    uint8
 51  Diab_2            786 non-null    uint8
 52  Diab_3            786 non-null    uint8
dtypes: float64(24), int64(19), uint8(10)
memory usage: 277.9 KB

In [ ]:
# Columnas de interes

col_interes = ['SaludFisica','SaludMental','Hip_1','Hip_2',
               'Hip_3','Hip_4','DiagColesterol','DiagAtaqCorazon','DiagEnfCorazon',
               'DiagDerrCerebral','Sexo','Peso','Altura','IMC','Fumar100',
               'UsTabSH_1','UsTabSH_2','UsTabSH_3','CantDiaAlc30dias','JugFru30dias',
               'Fruta30dias','Leg30dias','VerVerde30dias','VerNar30dias','OtrVer30dias',
               'Ejerc30dias','Diab_1','Diab_2','Diab_3']
df_final = df[col_interes]
df_final

,SaludFisica,SaludMental,Hip_1,Hip_2,Hip_3,Hip_4,DiagColesterol,DiagAtaqCorazon,DiagEnfCorazon,DiagDerrCerebral,Sexo,Peso,Altura,IMC,Fumar100,UsTabSH_1,UsTabSH_2,UsTabSH_3,CantDiaAlc30dias,JugFru30dias,Fruta30dias,Leg30dias,VerVerde30dias,VerNar30dias,OtrVer30dias,Ejerc30dias,Diab_1,Diab_2,Diab_3
0,0.500000,0.600000,1,0,0,0,1,-1,-1,-1,-1,0.617834,0.515306,0.730997,1,0,0,1,-2.051020,0.050505,0.101010,0.202020,1.111111,0.050505,-2.010101,-1,0,0,1
1,0.000000,0.000000,0,0,1,0,-1,-1,-1,-1,-1,0.251592,0.505102,0.318544,1,0,0,1,-2.051020,0.020202,0.050505,0.020202,-10.888889,-0.989899,0.040404,1,0,0,1
3,1.000000,1.000000,1,0,0,0,1,-1,-1,-1,-1,0.299363,0.500000,0.375987,-1,0,0,1,-2.051020,-3.030303,-2.010101,-3.030303,0.111111,0.010101,-1.000000,-1,0,0,1
5,0.000000,0.000000,1,0,0,0,-1,-1,-1,-1,-1,0.187898,0.474490,0.258169,-1,0,0,1,-2.051020,-2.010101,-2.010101,-2.000000,-22.111111,-2.000000,-2.010101,1,0,0,1
6,0.000000,0.100000,1,0,0,0,1,-1,-1,-1,-1,0.197452,0.494898,0.260675,-1,0,0,1,0.020408,0.303030,-0.989899,0.020202,-10.888889,0.020202,-0.959596,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,0.066667,0.000000,1,0,0,0,-1,-1,-1,-1,-1,0.283439,0.489796,0.362731,-1,0,0,1,0.030612,-3.030303,-2.000000,-3.030303,-22.111111,0.151515,0.151515,1,1,0,0
992,0.000000,0.000000,1,0,0,0,-1,-1,-1,-1,-1,0.171975,0.474490,0.239448,-1,0,0,1,0.295918,0.303030,-0.989899,0.303030,-10.777778,-0.989899,0.303030,-1,0,0,1
993,0.000000,0.000000,0,0,1,0,-1,-1,-1,-1,1,0.522293,0.515306,0.622169,1,0,0,1,-2.051020,-0.989899,-0.979798,-3.030303,-10.888889,-0.989899,-0.989899,1,0,0,1
994,0.000000,0.000000,0,0,1,0,-1,-1,-1,-1,-1,0.245223,0.494898,0.315953,-1,0,0,1,-2.051020,-3.030303,-2.000000,0.020202,-10.777778,0.050505,-2.000000,1,1,0,0
999,0.000000,0.066667,1,0,0,0,1,-1,-1,-1,-1,0.210191,0.484694,0.279870,-1,0,0,1,-2.051020,-0.979798,-2.000000,-1.000000,-22.111111,-0.979798,-2.000000,1,0,1,0

In [ ]:
# Finalmente, guardar el csv (sin el index)
#df_final.to_csv("/content/drive/MyDrive/data/resultados.csv", 
 #               index=False)
df_final.to_csv("/content/drive/MyDrive/data/resultadosMuestra.csv", 
                index=False)